### ISSUE TITLE
Improvement

### ISSUE THREAD

**Issue by marcosbong73** [mtheall/ftpd#101]
Sorry, but I'm a newbie using github and don't know where to suggest this.
It would be nice, if possible, to show battery level on ftpd screen, and keep ftpd transfering files if the console lid is closed. 
Thanks

**Comment by mtheall** [comment]
Battery status coming in v3.0.0. Need to look into the console lid closed part.

**Comment by marcosbong73** [comment]
Thanks, dude !!
If you are able to make the app work with the lid closed, it would save some battery. That would be really nice. 
Cheers

**Comment by mtheall** [comment]
That was part of the reason for using start button to turn off screens

**Comment by marcosbong73** [comment]
Man, I didn´t know that trick
If I knew that, I wouldn´t suggest the closed lid option
Sorry for messing with it

**Comment by mtheall** [comment]
It must be possible because microSD management app can do it.

**Comment by mtheall** [comment]
I'm not going to try and chase down the "make it work with the lid closed" for now.

**Comment by marcosbong73** [comment]
Ok. 
No problem at all. With the start button function is more than enough. 
Thanks a lot. 
Cheers

⁣Marcos

Obtener BlueMail para Android ​
