### ISSUE TITLE
Compile error:  'SDMC_DIRITER_MAGIC' undeclared 

### ISSUE THREAD

**Issue by xpirad** [mtheall/ftpd#106]
D:/3ds/ftpd/source/ftp.c: In function 'list_transfer':
D:/3ds/ftpd/source/ftp.c:2367:19: error: 'SDMC_DIRITER_MAGIC' undeclared (first use in this function); did you mean 'ARCHIVE_DIRITER_MAGIC'?
 2367 |       if(magic == SDMC_DIRITER_MAGIC)
      |                   ^~~~~~~~~~~~~~~~~~
      |                   ARCHIVE_DIRITER_MAGIC
D:/3ds/ftpd/source/ftp.c:2367:19: note: each undeclared identifier is reported only once for each function it appears in
D:/3ds/ftpd/source/ftp.c:2369:9: error: unknown type name 'sdmc_dir_t'
 2369 |         sdmc_dir_t        *dir   = (sdmc_dir_t*)session->dp->dirData->dirStruct;
      |         ^~~~~~~~~~
D:/3ds/ftpd/source/ftp.c:2369:37: error: 'sdmc_dir_t' undeclared (first use in this function)
 2369 |         sdmc_dir_t        *dir   = (sdmc_dir_t*)session->dp->dirData->dirStruct;
      |                                     ^~~~~~~~~~
D:/3ds/ftpd/source/ftp.c:2369:48: error: expected expression before ')' token
 2369 |         sdmc_dir_t        *dir   = (sdmc_dir_t*)session->dp->dirData->dirStruct;
      |                                                ^
D:/3ds/ftpd/source/ftp.c:2370:40: error: request for member 'entry_data' in something not a structure or union
 2370 |         FS_DirectoryEntry *entry = &dir->entry_data[dir->index];
      |                                        ^~
D:/3ds/ftpd/source/ftp.c:2370:56: error: request for member 'index' in something not a structure or union
 2370 |         FS_DirectoryEntry *entry = &dir->entry_data[dir->index];
      |                                                        ^~
D:/3ds/ftpd/source/ftp.c:2398:20: warning: implicit declaration of function 'sdmc_getmtime' [-Wimplicit-function-declaration]
 2398 |           if((rc = sdmc_getmtime(session->buffer, &mtime)) != 0)
      |                    ^~~~~~~~~~~~~
make[2]: *** [/opt/devkitpro/devkitARM/base_rules:85: ftp.o] Error 1
make[1]: *** [Makefile.3ds:141: 3dsx] Error 2
make[1]: Leaving directory '/d/3ds/ftpd'
make: *** [Makefile:30: 3dsx] Error 2

I'm using msys2 and mingw64-gcc 9.3. How to fix this?

**Comment by xpirad** [comment]
I've installed all 3ds-dev package and updated to the latest version.

**Comment by mtheall** [comment]
this is already fixed in the v3.0.0 branch
