### ISSUE TITLE
Random / added when executing RNTO command

### ISSUE THREAD

**Issue by la44446510** [mtheall/ftpd#109]
For example, if I move something from /3ds to /gm9 it adds an extra / on the receiver. It makes gm9 folder into //gm9 and errors out. 
![image](https://user-images.githubusercontent.com/43479533/83315304-ddd33800-a1d3-11ea-86ec-30bf45a15c67.jpg)

**Comment by mtheall** [comment]
That's the way your client is sending the path, so that part is a client-side problem. What client are you using?

However, I should be handling consecutive / just fine. Are you sure "/gm9/out/CIA Dumps" exists?

**Comment by la44446510** [comment]
Yes, it exists on the 3ds. This happens when I try to move anything anywhere

**Comment by mtheall** [comment]
Thanks, will investigate

**Comment by mtheall** [comment]
Fixed in bae8254
