### ISSUE TITLE
files to generate cia

### ISSUE THREAD

**Issue by hippydave** [mtheall/ftpd#11]
http://gbatemp.net/attachments/ftbrony-zip.12403/

I don't know pull requests ;P I built and added images and rsf to make a .cia, feel free to use/abuse/delete as you see fit. Cheers for awesome app!

**Comment by mueee** [comment]
@hippydave Could you provide your method to build this as a CIA? You removed your original file and I don't want to have to rely on others to have the latest version as a CIA. suloku's version posted yesterday is already outdated.

**Comment by mtheall** [comment]
Due to the growing popularity of ftbrony, and in order to help consolidate the many forks, I will now accept pull requests which enable ftbrony to be built as a .cia. I have no way of testing .cia, but if someone else wants to provide a build to me for each release I can post the binary for it.

**Comment by m45t3r** [comment]
If someone can provide a banner.bin and an icon.bin file, generating a CIA from Makefile is not difficult: https://github.com/m45t3r/3DS_Quick_Reboot/blob/master/Makefile#L148

**Comment by m45t3r** [comment]
I decided to give it a shot: https://github.com/m45t3r/ftpd

I can make a PR, however I don't know if @mtheall will accept it. There is some pretty invasive changes, including a complete rewrite of Makefiles to use [Steveice10/buildtools](https://github.com/Steveice10/buildtools). However it works. If @mtheall thinks it is ok to merge I will do a PR, if not I can maintain this fork separated.

The resulting file can be found below:
[ftpd.zip](https://github.com/mtheall/ftpd/files/110382/ftpd.zip)

**Comment by mtheall** [comment]
I created a cia branch; see 7e86040

**Comment by m45t3r** [comment]
@mtheall hey, thanks! I will delete my fork now.
