### ISSUE TITLE
"No route to host"

### ISSUE THREAD

**Issue by slender15** [mtheall/ftpd#112]
Hi, I've been trying to connect ftpd of my 3ds to my phone but every time I try it it gives me an " (ip) couldnt connect to (ip) EHOSTUNREACH: no route to host"

I also tried using filezilla but it gives the same result, any help?

**Comment by WinterMute** [comment]
We need some more details of what it is you're trying to do.

Are you using your phone as a hotspot and using filezilla from another device?

**Comment by slender15** [comment]
Oh, sorry if I wasn't clear.
What I mean is that I try to transfer files from my phone to my 3ds, but I get the error mentioned when I try to connect to the 3ds ftpd, and if I try to connect using filezilla from my pc instead, I also get a connection failed error.

**Comment by WinterMute** [comment]
OK. The chances are that the network you're connecting to is set up to isolate clients from each other. You'll need to disable AP (access point) isolation -- also known as 'Client Isolation' or 'Guest Mode' -- on your router. You'll need to check your router manual to figure out how to do that.

If you don't have access to your router configuration - if you're using a guest or public network with client isolation then unfortunately you won't be able to ftp to your 3ds.

**Comment by WinterMute** [comment]
Still curious though. Did you fix it or do you not have the required access?

**Comment by slender15** [comment]
I fixed it, AP was somehow enabled when I checked router settings. I disabled it and I could transfer normally files between phone and 3ds. Thanks for your help and time
