### ISSUE TITLE
connection cannot be established

### ISSUE THREAD

**Issue by klutch5398** [mtheall/ftpd#114]
**Describe the bug**
I don't think this is necessarily a bug, rather something that is blocking the connection to my switch? I get the following Error Everytime I try to connect. 
Windows cannot connect access this folder. Make sure you typed the file name correctly and that you have permission to access this folder. 
Details: A connection with the server cannot be established

Not sure if there are any permissions that are actively blocking this connection, as my PC seems fine to connect and my Bitdefender isn't blocking any connections. 
I Will attach screenshots here: 
![download](https://user-images.githubusercontent.com/69431446/89804433-2a0af480-db02-11ea-8ab1-8ea96b6dd8b9.jpg)
![download (1)](https://user-images.githubusercontent.com/69431446/89804438-2b3c2180-db02-11ea-8841-511274dcf748.jpg)

**Platform (please complete the following information):**
- System Nintendo Switch
- System version 10.1.0
- Launch method Atmosphere - 0.14.1
- Type Switch V1
- Classic? No

**Comment by klutch5398** [comment]
![download (2)](https://user-images.githubusercontent.com/69431446/89804787-9c7bd480-db02-11ea-9b9d-6e113d788dc8.jpg)

**Comment by mtheall** [comment]
Looks like you didn't specify to connect using port 5000.

**Comment by klutch5398** [comment]
@mtheall I did, after I click enter, it doesn't show the 5000 part and automatically reverts to what the screenshot says.

I type in the following:
ftpd://192.168.1.220:5000

**Comment by klutch5398** [comment]
I use sysbot on the switch and connect via IP with no problems while playing Animal Crossing

**Comment by mtheall** [comment]
Don't put the 'd' in ftpd in the URL

**Comment by klutch5398** [comment]
it normally takes out the 'd' when I had originally typed it in that way. 

I went ahead and typed it in ftp://192.168.1.220:5000

However, same error message :(

**Comment by mtheall** [comment]
Do you have a way for me to contact you for live support?

**Comment by klutch5398** [comment]
Yes, how should we go about this? You can email me directly if you'd like railsplitter360@gmail.com
And we can figure something out!

**Comment by klutch5398** [comment]
@mtheall just went ahead and messaged you! :)

**Comment by mtheall** [comment]
Client-side issue: firewall settings
