### ISSUE TITLE
Increase transfer speed

### ISSUE THREAD

**Issue by trezzam** [mtheall/ftpd#119]
Hi, 
FTPD is perfectly working on my Switch, but maximum transfer rate is around 4Mbps. That's not bad, but for large files it takes up to 30 minutes :-(
I tested it from different clients, and the result is similar. Is it a problem of my LAN? Did you reach better transfer rates in your tests?

Thanks for your work, it's great!

**Comment by mtheall** [comment]
Your effective speed is going to depend on many variables, for example:
- SD card
- WiFi proximity
- Phase of the moon

I've done basically everything I can to get the best performance, but at the end of the day the Switch is not designed for this kind of workload. I could get anywhere between 500KiB/s to 5MiB/s for back-to-back tests. To really see gains, we'd probably need replace the Switch's network and filesystem services, which would be quite an undertaking.

It's possible that using a wired LAN adapter may help, but I haven't been able to test that.

I have worked on adding MODE Z support (zlib compression), but *very* few FTP clients support it. This could improve transfer times, but heavily depends on the compressibility of your data.
