### ISSUE TITLE
Closing connection automatically

### ISSUE THREAD

**Issue by Chexet48** [mtheall/ftpd#123]
When transferring files from Android to 3DS, it closes automatically the connection to my phone. Here is the screenshot.
![IMG_20201103_012840~2](https://user-images.githubusercontent.com/13398399/97934037-c3018280-1d74-11eb-8997-f4d7b6d2823a.jpg)

**Comment by mtheall** [comment]
Looks like a client that's not properly following the protocol. I can add an exception for PWD to be allowed during transfers.

**Comment by Chexet48** [comment]
I have tried several clients but all do this. I really don't know what It could be, but if you say you can add an exception, I would be pleased.

**Comment by Chexet48** [comment]
@mtheall Can you send me a version of FTPD with the PWD exception? That command is sure the problem

**Comment by mtheall** [comment]
Try adding it here:
https://github.com/mtheall/ftpd/blob/691c98e956121a7378fc8443f987cfb03594b739/source/ftpSession.cpp#L1481-L1482

What client are you using? I have never encountered this.

**Comment by Chexet48** [comment]
I tried to use FIleZilla, PowerFTP, your FTP for Android and AndFTP

**Comment by Chexet48** [comment]
@mtheall Ok edited and recompiled. It doesn't give me the closing connection message anymore, but when the PWD command executes, it just stops uploading the file(s). I don't know what it could be.

**Comment by Chexet48** [comment]
@mtheall I noticed FTPD has this "error" every time I upload a file, it does this after 15-20 seconds. What could it be?

**Comment by RetroPKMN** [comment]
I have the same problem ! It closes automatically the connection !

I'm on atmosphere 0.15 and FTPD pro 3.0.0 , same for FTPD classic 3.0.0

**Comment by mtheall** [comment]
I've finally been able to recreate this now with PowerFTP by turning on the Keep-Alive option.
