### ISSUE TITLE
Can't download files

### ISSUE THREAD

**Issue by Sethyboi1** [mtheall/ftpd#124]
It would be nice if you could download files from your 3DS system. Personally, this is useful for ACNL save editing, since you need your town's "garden_plus.dat" file. Right now, every time I want to edit something, I have to unscrew my 3ds, insert it, get the file, and then I can edit it. IDK if this is possible on the 3DS, but if it is, PLEASE add it. (:

**Comment by Masamune3210** [comment]
If you are talking about copying files from your 3ds sd card to your comp using ftp, then you already can?

**Comment by Sethyboi1** [comment]
I'm using FileZilla on my comp and it won't let me.

**Comment by Sethyboi1** [comment]
https://imgur.com/a/i7qfPk6

**Comment by Sethyboi1** [comment]
k I figured it out, if I edit the file, I can save it on my pc.
