### ISSUE TITLE
Clear Text Field Feature

### ISSUE THREAD

**Issue by mitkan191003** [mtheall/ftpd#125]
**Sorry if this is a repeat, but for whatever reason, my FTP applications, Cyberduck and WinSCP, do not work with FTPD's password system.**
On Cyberduck: I repeatedly get "**Interoperability Failure**:    430 invalid password" errors even after establishing a connection to my new 3ds xl. For example, I will enter a username and password when opening a connection, and I am able to view, download, and delete files on my 3ds. As soon as I start an upload, however, it errors and refuses to work. Uninstalling and reinstalling FTPD doesn't reset the username and password.

On WinSCP: Does not connect at all.

Because I'll be doing transfers at home, I would rather delete the username and password (How FTPD was when I installed it) instead of troubleshooting. I would appreciate some way to clear the text fields since the 3ds keyboard does not seem to let you. Uninstalling and reinstalling FTPD doesn't work.

If this isn't possible, maybe a checkbox that enables the authentication would work.

If all else fails, could you point me to the settings/config file? Maybe I could edit the password from there.

I am running FTPD v3.0.0 on the latest version of Luma3DS on firmware 11.14.0-46U if that helps.

**Comment by mtheall** [comment]
I have recently noticed that clearing a text field wasn't working (on Switch, didn't investigate 3DS yet) but I haven't dig into trying to fix it yet. I was planning to add a "clear" button.

**Comment by mitkan191003** [comment]
Alright, thanks. Any idea of when you'll finish?

**Comment by mtheall** [comment]
Sorry, I don't do ETAs

**Comment by mtheall** [comment]
Added reset button with 607ca560

**Comment by mitkan191003** [comment]
For anyone that is experiencing the same authentication issues, it is because the 3ds uses SMB 1.0 protocols, which are disabled by default on windows for security reasons.

**To fix this:**
1. Type "Turn Windows features on or off" into the start menu searchbar.
2. Scroll down until you find "SMB 1.0/CIFS File Sharing Support"
3. Press the plus on the left of the folder icon to expand the category.
4. Turn on "SMB 1.0/CIFS Client" and "SMB 1.0/CIFS Server"
5. Click "OK" and follow the prompts to restart your computer.
6. FTPD should be able to connect now.

## Make sure to disable SMB 1.0 once you are done because it is very outdated and super insecure.

**Comment by mtheall** [comment]
Uhh that has nothing to do with ftpd

**Comment by mitkan191003** [comment]
Sorry, just felt that it wouldn't hurt to comment that. In case anyone else comes here with the same problem.
