### ISSUE TITLE
Can this be installed to NAND?

### ISSUE THREAD

**Issue by teelolws** [mtheall/ftpd#131]
Is there a way to install this to the NAND, so that I can use it to read SD cards that don't already have homebrew installed on it? For 3DS.

**Comment by mtheall** [comment]
.cia

**Comment by teelolws** [comment]
The .cia only installs to SD. Got instructions to make it install to NAND instead?

**Comment by mtheall** [comment]
Looks like maybe https://github.com/mtheall/ftpd/blob/master/meta/ftpd-classic-cia.rsf#L11 ?
Try changing that to false
