### ISSUE TITLE
Let me set a port lower than 1024, particularly the default 21 for FTP

### ISSUE THREAD

**Issue by Yrouel** [mtheall/ftpd#134]
I'd like to be able to set the default 21 port for FTP, is there any particular reason why the application is hardcoded not to let the user set ports lower than 1024?

**Comment by mtheall** [comment]
On platforms where the sockets lib allow (NDS, 3DS), this is already available. The Switch OS won't allow privileged ports.

https://github.com/mtheall/ftpd/blob/d648a8dca73676036e0907d21da1ca50feedb2b0/source/ftpConfig.cpp#L284-L298

**Comment by Yrouel** [comment]
Well then this just turned a bug report, I filed this issue after I was trying to set the port to 21 both from the app and then manually changing it in the config file it still started with 5000 no matter what I tried

**Comment by mtheall** [comment]
How's this? 9c1735e3

**Comment by Yrouel** [comment]
> How's this? [9c1735e](https://github.com/mtheall/ftpd/commit/9c1735e33f9335e6cd5bbc45f0e256b437b8e7f3)

I didn't know you could set port 0 on the Switch. If you just ignore that edge case you can use the more compact code I wrote above if it's sound otherwise yours works too I guess

**Comment by mtheall** [comment]
Yes port zero means the OS assigns a port, so effectively you'd get a random port every time you started the server.

**Comment by ITotalJustice** [comment]
> On platforms where the sockets lib allow (NDS, 3DS), this is already available. The Switch OS won't allow privileged ports.
> 
> https://github.com/mtheall/ftpd/blob/d648a8dca73676036e0907d21da1ca50feedb2b0/source/ftpConfig.cpp#L284-L298

fwiw, as long as the socket is initialised with `BsdServiceType_System`, then you can use privileged ports such as port 21 on the switch.
