### ISSUE TITLE
Connection speed dramatically lessens (10 kb/s) mid-transfer

### ISSUE THREAD

**Issue by NathanYumekoe** [mtheall/ftpd#135]
**Describe the bug**
Connection speed dramatically lessens (10 kb/s) for reasons I legitimately can not figure out

**To Reproduce**
1. Transfer a file
2. For some reason, different files behave differently. An .nds file may have it happen either instantly or after around 70 MB, and the same .nds file packed into a .zip is instead transferring flawlessly. Another .nds file also has it happen either instantly or after around 70 MB, but upon packing that one into a .zip it happens after around 40-50 MB. It also happens with .3dsx files, where for example a 700 KB 3dsx file will go down to 10-20 kb/s after 500 KB.
3. The only way I can find 

**Expected behavior**
The file transfers at a constant rate.

**Screenshots**
https://imgur.com/a/jr5TIaR

**Platform (please complete the following information):**
- System [e.g. 3DS] 3DS
- System version [e.g. 11.13.0-45] 11.14.0-46E
- Launch method [e.g. rosalina 2.0.0] Tried both cia and rosalina 2.1.1
- Type [e.g. 3dsx] cia and 3dsx
- Classic? [Yes/No] both

**Additional context**
This didn't use to happen last time i tried, which I'm unsure when it was but I'm sure wasn't that long ago. As far as I'm aware nothing should have changed since then, yet here we are. An important note is I updated ftpd with universal-updater to the latest version, from 3.0 to 3.1, yet when i tried downgrading to 3.0 it still kept this issue.

**Comment by mtheall** [comment]
Sorry transfer speeds are out of my control. WiFi speed on the 3DS is highly variable and susceptible to signal quality

**Comment by NathanYumekoe** [comment]
It does not have to do with the WiFi connection. Other things (universal-updater, FBI, etc) work perfectly fine.

**Comment by mtheall** [comment]
See #113

**Comment by NathanYumekoe** [comment]
I am a little confused by the speed test but I will try it. However, do note the difference in those cases. Mine starts at the correct speed for most of the download most of the time, theirs is consistently low.

**Comment by NathanYumekoe** [comment]
Okay, i can not figure out how to work that speedtest thing...

**Comment by mtheall** [comment]
If the speed test maintains a consistent rate, then that points to SD card problem. If the speed test still slows down, that points to a wifi problem.

**Comment by NathanYumekoe** [comment]
I would try it, but I have legitimately no idea how to "read/write to a fake file named /devZero"

**Comment by mtheall** [comment]
Which FTP client are you using?

**Comment by NathanYumekoe** [comment]
WinSCP

**Comment by NathanYumekoe** [comment]
Nevermind, figured out how to do it via curl. It is mantaining a consistent rate, but that is even weirder I'd argue, since litterally everything other than ftpd works.

**Comment by NathanYumekoe** [comment]
Writing a fake real file also seems to have no issues, found out by accidentally typing devZer0

**Comment by NathanYumekoe** [comment]
okay I am sorry for bothering since this is apparently an issue of my computer specifically.

**Comment by mtheall** [comment]
I found something about "disable Connection -> Optimize connection buffer size" in WinSCP helping with transfer speeds. You could also try another client like FileZilla to see if there's a difference.

**Comment by profi200** [comment]
I don't think it's a problem with the SD cards themselves. I have seen this effect before where if you write to 0 byte files writing can hang for a while because it's searching for free clusters in the middle of the write. The obvious solution is pre-allocating the clusters for the file (ftruncate).

Also for me speed is fluctuating a lot. It alternates between stalling (0 bytes/s) and 1.1 MiB/s. The client is Thunar's (Linux with xfce) builtin FTP server support.

**Comment by mtheall** [comment]
Preallocate would be great but unfortunately FTP STOR doesn't tell you file size before transfer. There is the ALLO command but I don't know a client that uses it, so I have it as a no-op.
