### ISSUE TITLE
When ftpd is downloaded  from the Homebrew Appstore it only downloads the classic version not both.

### ISSUE THREAD

**Issue by Troy2424** [mtheall/ftpd#137]
It used to download the pro version and classic version. Now it just downloads the classic one, which isn't the one I want to use. It's not a big deal but it just makes it easier to update if I can go through the HB appstore to update and get the version I want.

**Comment by mtheall** [comment]
I don't know what the "Homebrew Appstore" is. Contact them for this problem.
