### ISSUE TITLE
Installation issues

### ISSUE THREAD

**Issue by MeBULaTuDE** [mtheall/ftpd#138]
**Describe the bug**
I'm attempted to install ftpd on my NEW Nintendo 3DSXL through both FBI and HOMEBREW, but neither work. CIA either fails to install, or doesn't give me the option to install and delete the cia file. As for the HOMEBREW method, it just crashes my 3ds every time I even select it.

**Comment by Masamune3210** [comment]
what is the error given when trying to install it
