### ISSUE TITLE
Got the 550 I/O error on latest OFW 13.0.0 @ AMS 1.1.0pre

### ISSUE THREAD

**Issue by JrRadiant** [mtheall/ftpd#139]
**Describe the bug**
When trying to connect via my PC, I've "550 I/O" error with latest OFW 13.0.0 @ AMS 1.1.0pre. Screenshot is attached down below.

**To Reproduce**
1. Open program.
2. Trying to connect
3. Got the error.

**Screenshots**
![scr](https://user-images.githubusercontent.com/61790774/134188323-0da2742e-b2c4-454a-b63a-a28ef112cfcb.jpg)

**Platform (please complete the following information):**
- Switch
- OFW 13.0.0, AMS 1.1.0pre
- hbmenu
- Classic: Yes

**Comment by JrRadiant** [comment]
Tried two clients: the native Windows Explorer one, and the FileZilla. Both shows that error. The FZ log is:
```
Status:	Connecting to 192.168.100.5:5000...
Status:	Connection established, waiting for welcome message...
Status:	Plain FTP is insecure. Please switch to FTP over TLS.
Status:	Logged in
Status:	Retrieving directory listing...
Command:	PWD
Response:	257 "/"
Command:	TYPE I
Response:	200 OK
Command:	PASV
Response:	227 Entering Passive Mode (192,168,100,5,111,68).
Command:	MLSD
Response:	150 Ready
Response:	550 I/O error
Error:	Failed to retrieve directory listing
```

**Comment by JrRadiant** [comment]
Yep, the number is 1703, full screenshot:

![scr2](https://user-images.githubusercontent.com/61790774/134210225-ac85816d-6ec2-4a11-8264-0b033f41f5e0.jpg)

**Comment by JrRadiant** [comment]
Here you are:

![scr3](https://user-images.githubusercontent.com/61790774/134211532-698ba733-0fd0-4a62-af04-6ef20b381684.jpg)

Btw my bootloader folder is protected by Hekate 5.6.2:

> _bootprotect=1 | Protect bootloader folder from being corrupted by disallowing reading or editing in HOS._

More info here: https://github.com/CTCaer/hekate#hekate-global-configuration-keysvalues-when-entry-is-config
Maybe ftpd can live with it? It was totally OK with that option until FW 13.0.0..

**Comment by mtheall** [comment]
I would prefer hekate to make it read-only instead of error

**Comment by Frescone** [comment]
Hi there! thank you for all the work you do here and for reading!

I have the same problem with the same build OFW 13.0.0 @ only with AMS 1.2.0 (pre) Hekate 5.6.4. Tried both classic, pro, and debug. Here are the screen shots of the last one:

![2021102117083000-22A4BDEA5363AAA24F931D5AF2926082](https://user-images.githubusercontent.com/68090853/138237952-74d93f17-4da4-4750-aa6a-2c23bee99f71.jpg)
![2021102117080600-22A4BDEA5363AAA24F931D5AF2926082](https://user-images.githubusercontent.com/68090853/138237933-a7951102-076c-4509-bafc-5db1396a23c9.jpg)


I am not sure how was fixed it in the past but I hope this can help!

Thank you again!

**Comment by mtheall** [comment]
@ToxiClay can you try https://mtheall.com/~mtheall/ftpd-139.nro

**Comment by ToxiClay** [comment]
Perfect. Works properly even with bootprotect enabled. Thank you for the quick turnaround!

I guess now is to start prodding the sys-FTPD devs to fix the sysmodule versions; hopefully it's not too intensive.

![2022033112184800-DB1426D1DFD034027CECDE9C2DD914B8](https://user-images.githubusercontent.com/13796683/161102885-64e5f3c4-5ce9-4f18-b927-e9cc01cc5ea3.jpg)

**Comment by mtheall** [comment]
How does `/bootloader` show up in your ftp client? As a regular file with all-zero attributes?

**Comment by ToxiClay** [comment]
Yep. Permissions set to `df (00)` -- that sounds like something Linux users would know more about than I would, being a Windows dork.

![image](https://user-images.githubusercontent.com/13796683/161103454-31a424d8-81bb-48b5-a340-15d3a5534d6d.png)

**Comment by mtheall** [comment]
9f31cde4ee
