### ISSUE TITLE
Can not transfer files with non-latin characters in file name

### ISSUE THREAD

**Issue by alexkirs** [mtheall/ftpd#141]
**Describe the bug**
Can not transfer files with non-latin characters in file name. When try to copy such file - in ftpd console I see wrong filename, it looks like ascii symbols mess.

**To Reproduce**
Try to copy or create file with "абсдеф.txt" name for example.

**Platform (please complete the following information):**
- Switch

**Comment by eku** [comment]
Does the filesystem driver of the switch support unicode?

**Comment by alexkirs** [comment]
> Does the filesystem driver of the switch support unicode?

I think you right. It seems like switch filesystem driver does not support unicode. When I try to copy same files over MTP - they did copy but all non-english characters replaces with empty char.

![2021100518455600-49F3AB1FEC27E3CC1D94E9D4AD7DA138](https://user-images.githubusercontent.com/1640869/136017203-0c9f518f-463d-4bee-9fb3-31490a695f2e.jpg)

Maybe then there is sense to do same in ftpd? Replace all non-english characters with empty char. Or even better - transliterate them?

**Comment by mtheall** [comment]
This is a Switch OS bug, not an ftpd one. I would expect that MTP did the same thing as ftpd; the blank characters are display-only due to limited font.
