### ISSUE TITLE
 Got the 550 I/O error on latest OFW 13.0.0 @ AMS 1.2.0pre

### ISSUE THREAD

**Issue by Frescone** [mtheall/ftpd#142]
**Describe the bug**
 When trying to connect via OSx or PC, I've "550 I/O" error with latest OFW 13.0.0 @ AMS 1.2.0pre. The screenshot is attached down below. It is exactly the same bug reported in issue  #139 only I am on the latest release of atmosphere (1.2.0 pre) and Hekate (5.6.4).

**To Reproduce**

1 Open program.
2 Trying to connect
3 Got the error.

**Screenshots**

![2021102117083000-22A4BDEA5363AAA24F931D5AF2926082](https://user-images.githubusercontent.com/68090853/138237952-74d93f17-4da4-4750-aa6a-2c23bee99f71.jpg)
![2021102117080600-22A4BDEA5363AAA24F931D5AF2926082](https://user-images.githubusercontent.com/68090853/138237933-a7951102-076c-4509-bafc-5db1396a23c9.jpg)

**Platform (please complete the following information):**
unpatched switch OFW 13.0.0 AMS 1.2.0pre Hekate 5.6.4
Tried both classic, pro, and debug. I attached the screenshots of the last one.
On OSx and Windows.

Thank you for your work!

**Comment by Frescone** [comment]
@Masamune3210 Thank you! it seems to have worked!

**Comment by Masamune3210** [comment]
No problem! Mac's tend to mess up extended bits on anything they touch so I tend to just assume by default that archive bits at the least are probably wrong
