### ISSUE TITLE
Shut down SYS-FTPD when starting FTPD app and shut down when closing

### ISSUE THREAD

**Issue by fennectech** [mtheall/ftpd#144]
**Is your feature request related to a problem? Please describe.**
FTPD is much faster than sys-ftpd but its nice to have SYS-FTPD running in the background

**Describe the solution you'd like**
Shut down SYS-FTPD when starting the app and start it back up when closing the app 

**Describe alternatives you've considered**
Dont think theres a better way

**Additional context**
When transferring large files like dumps down off my switch i like to use the FTPD APP instead of the slower sys-which is good for smaller transfers like editing cheats and pulling logs.   However. To use the app i have to manually shut down sys-ftpd and restart it when closing this app.   It would be awesome if the app could do it automaticly.  And it shouldent be that difficult to kill and restart upon closing and opening

**Comment by mtheall** [comment]
I don't know what is sys-ftpd.

**Comment by fennectech** [comment]
Its a sysmodule that provides FTPD access with the title ID of 420000000000000E

Just kill that module when starting up and start it up when exiting this application

**Comment by fennectech** [comment]
https://github.com/WerWolv/ovl-sysmodules  This here starts and stops sysmodules https://github.com/WerWolv/ovl-sysmodules. (You can ignore the filesystem part as your not modifying the start at boot status of the sysmodule

**Comment by mtheall** [comment]
Sorry, that is GPLv2 and ftpd is GPLv3. Also, I won't be in the business of managing the runtime of external apps and services.

**Comment by fennectech** [comment]
Alright.  Thanks for the input.
