### ISSUE TITLE
Keep the FTP server up when 3ds lid is closed

### ISSUE THREAD

**Issue by bebewold** [mtheall/ftpd#154]
**Is your feature request related to a problem? Please describe.**
I would like my 3ds server to stay up when I close the lid, I'm not using the 3ds when transfering files to it so i have the habit of closing the lids when using ftpd, which close the server 

**Describe the solution you'd like**
I want the server to stay up until I close the app, lid open or not

**Comment by mtheall** [comment]
The OS turns off wifi when you close the lid

**Comment by bebewold** [comment]
There's app like hshop that doesn't stop the process when the lid is closed, it stills installs. Is their something different between keeping a server up and downloading and installing a file?

**Comment by mtheall** [comment]
If there's a way to do it, I don't know what that way is.

**Comment by eku** [comment]
@bebewold What is the reason for closing the lid? If it's just to save power to the screens, then press SELECT and ftpd will turn them off.

**Comment by bebewold** [comment]
It's more of a habit, when I put away I close the lid but when I do that with ftpd I lose connection, and it doesn't happen with the other app I use

**Comment by eku** [comment]
@bebewold could please name one of the homebrew that keeps wifi in and is available as source?

**Comment by profi200** [comment]
You are probably looking for "[Runnable on sleep](https://www.3dbrew.org/wiki/NCCH/Extended_Header#ARM11_Kernel_Flags)" which is not available for 3dsx homebrew iirc.

**Comment by bebewold** [comment]
> @bebewold could please name one of the homebrew that keeps wifi in and is available as source?

The app is named hshop, I can't find it on GitHub but they source cod is available on their site: https://hshop.erista.me/3hs

Godmode9 also does keep working when you close the lid, but it loads up before the OS I think? And doesn't use wifi so I see how that would be different. 

Hshop however runs on the OS and is installed using a CIA like I did with ftpd

**Comment by mtheall** [comment]
Looking at that source code, looks like they use aptSetSleepAllowed(false)
I just tried it and the 3DS wifi still turned off when I closed the lid.

**Comment by mtheall** [comment]
[16c5935](https://github.com/mtheall/ftpd/commit/16c59354da91cd869ddea14438ec71386aeb1b7a)
