### ISSUE TITLE
3DS version doesn't give you access to read content in folders that are 2 folders deep

### ISSUE THREAD

**Issue by ExperiencersInternational** [mtheall/ftpd#159]
Self-explanatory, the Nintendo 3DS version on a O3DS XL doesn't allow you to view any content in 2 folders deep, this also causes issues with not being able to delete stuff if there's content 2 folders deep.

Here's a screenshot (for context, this folder displays files that are used for the 3DS homebrew application, PinBox):

![Screenshot_2022-10-03-20-22-48-939_com mi android globalFileexplorer](https://user-images.githubusercontent.com/56035537/193662126-0f392742-b02b-4ab8-b472-6df18ff95688.jpg)

**Comment by mtheall** [comment]
What's the logs say on the 3DS?

**Comment by ExperiencersInternational** [comment]
Pretty much 550 No such file or directory.

![Screenshot_2022-10-03-21-30-26-286_com mi android globalFileexplorer](https://user-images.githubusercontent.com/56035537/193676456-efc0e6a1-1978-4aa3-954f-f3db1d620db2.jpg)

![16648290370394635620471256604893](https://user-images.githubusercontent.com/56035537/193676560-41ee6e42-b987-4608-995b-2b5dfdf5fdeb.jpg)

**Comment by mtheall** [comment]
Try the new Upload Log option

**Comment by ExperiencersInternational** [comment]
Just out of interest, how would you create a log and where would it be stored?

Will do it later today.

**Comment by mtheall** [comment]
Menu -> Upload Log
Uploads it to hastebin then shows you the URL

**Comment by ExperiencersInternational** [comment]
I checked that I was running the latest version, 3.1.0 and I don't see an upload log button.

![16648993431803161990084497829603](https://user-images.githubusercontent.com/56035537/193868857-4b3f0782-6ef0-4e25-82ac-a709882959bd.jpg)

**Comment by mtheall** [comment]
https://mtheall.com/~mtheall/ftpd.3dsx

**Comment by ExperiencersInternational** [comment]
hastebin.com/fakozijoxo

**Comment by ExperiencersInternational** [comment]
Just to prove there's files there

![16649017927912487995525317425598](https://user-images.githubusercontent.com/56035537/193878052-fc9ee14a-fb56-42ab-b6b3-8fb1475574ce.jpg)

**Comment by mtheall** [comment]
redownload and try again

**Comment by Tulip-0333** [comment]
It works perfectly fine for me, try changing your 3DS' time, or insert your SD card into your computer and use the "touch" command to set the modified date to the current time (or literally just modify the file). Also try reinstalling your ftpd.

**Comment by ExperiencersInternational** [comment]
> It works perfectly fine for me, try changing your 3DS' time, or insert your SD card into your computer and use the "touch" command to set the modified date to the current time (or literally just modify the file). Also try reinstalling your ftpd.

I'm guessing touch is a Linux exclusive command? Funnily enough, I linked this bug to someone the other day and I'm using a new FTP client now (since Xiaomi discontinued the one in the File Manager application) and it seems to work fine for me now. I have issues deleting or saving stuff at times though with the application.
