### ISSUE TITLE
MDTM command falsely implemented?

### ISSUE THREAD

**Issue by KewlSokudo** [mtheall/ftpd#160]
No matter which FTP client I use, the MDTM command just doesn't work and spits a 502 response at me. Probably because it isn't actually a feature of ftpd? It's listed in the README.md and even some strings in the source code mention it:

`void FtpSession::HELP (char const *args_)
{
    setState (State::COMMAND, false, false);
    sendResponse ("214-\r\n"
                  "The following commands are recognized\r\n"
                  " ABOR ALLO APPE CDUP CWD DELE FEAT HELP LIST MDTM MKD MLSD MLST MODE\r\n"
                  " NLST NOOP OPTS PASS PASV PORT PWD QUIT REST RETR RMD RNFR RNTO SITE\r\n"
                  " SIZE STAT STOR STOU STRU SYST TYPE USER XCUP XCWD XMKD XPWD XRMD\r\n"
                  "214 End\r\n");
}`

But there isn't any actual working code for it in ftpSession.cpp
What's with this?

**Comment by mtheall** [comment]
There is no API on the 3DS or Switch to be able to set a file's timestamp, and so therefore the MDTM is impossible to implement.
