### ISSUE TITLE
Renaming a file on client to same name without capital letters caused no such file or directory erorr

### ISSUE THREAD

**Issue by hYdos** [mtheall/ftpd#161]
**Describe the bug**
Renaming a file on client to same name without capital letters caused no such file or directory erorr

**To Reproduce**
1. Create a file called BOOT.NDS
2. Try rename the file to boot.nds
3. See error

**Expected behavior**
The file will be renamed to boot.nds

**Screenshots**
![image](https://user-images.githubusercontent.com/25501603/202932562-42193579-e361-4f64-aa74-1508168981aa.png)

**Platform (please complete the following information):**
- System 3DS
- System version Latest 11.16 EU
- Launch method Home Menu CIA
- Type CIA
- Classic? No

**Comment by Masamune3210** [comment]
Rename it something else and then rename it back to whatever you want but in Captials, Windows has the same limitation so it wouldn't be surprising if its a 3DS filesystem service limitation

**Comment by mtheall** [comment]
FAT32 is case-insensitive. It's an error to rename a file to itself.
