### ISSUE TITLE
ftpd requires working DNS despite being direct IP (3DS, but maybe all versions.)

### ISSUE THREAD

**Issue by Nazosan** [mtheall/ftpd#165]
**Describe the bug**
I was using a custom DNS server on a local server, but had to redo the server and no longer had the custom DNS server.  This caused the 3DS to be unable to get DNS in its connection, however, the actual connection would still come up and work 100% otherwise for direct connections (for example, I could use "MicroSD Management" in the system settings to connect via Windows network shares/CIFS.)  As an FTP server only receives connections, it does not actually need DNS and there isn't really any reason it should require it as long as the actual network connection itself is up.  I don't know if it's using it as some form of network checking (in which case that may not be good as it could mean a LAN with no Internet connection also won't work, but for local connections it should not require the Internet.)

This may or may not apply to the other versions.  I have not had the time to test it on my Switch and the NDS version presents its own difficulties to test on a 3DS since I don't have a NDS anymore (but I can probably do so later if need be.)  I would imagine they use similar enough methods that it would still apply however.

**To Reproduce**
1. Put in an invalid DNS server in connection settings manually.  (On Switch this may require having one that is valid and then invalidating it in some form such as an online DNS and then disconnecting the LAN from the Internet since checking the connection after changing the settings is not optional but the NDS and 3DS should not force a check.)
2. Verify in home screen that connection is up and has good signal strength (toggling wifi on if necessary.)
3. Start ftpd.
4. It will perpetually say "waiting for wifi" and will not accept incoming connections.

**Expected behavior**
A FTP server should not require or utilize DNS or even require an online connection at all.  As long as there is a valid WiFi connection and it has an IP address to bind to it should be ready to accept incoming connections.

**Platform (please complete the following information):**
- System: New 3DS (non-XL if it matters)
- System version: 11.16.0-49U (but probably doesn't matter.)
- Launch method: from both system launcher and homebrew launcher had the same results.
- Type: both the CIA and 3DSX versions had the same results.
- Classic?:  Both versions had the same results.

**Comment by Masamune3210** [comment]
It's not ftpd causing the issue, it's the system. The 3DS will refuse to do most network things if it can't do it's network check first, which requires functional DNS and the ability to contact outside servers. Until that check passes, almost everything network wise either won't work correctly or won't work at all

**Comment by Nazosan** [comment]
It's able to do the MicroSD management thing, so I do wonder if it's really just completely unable to proceed though?  I'm not sure of the inner workings of all this, but if it sees an IP address at all, can't it just bind to that without any need for checking other things?

**Comment by mtheall** [comment]
The MicroSD management app does not use the soc:u service. Instead it uses the nwm service which would require manually choosing and connecting to a wifi ap which is more complicated than I'm willing to implement.

Luma3DS provides a way to force a connection without connection test passing:
System configuration... -> Control Wireless connection -> Press A to force a connection to slot

**Comment by Masamune3210** [comment]
I was at work and completely forgot Luma has an option to do that now or I would have said that in the first place
