### ISSUE TITLE
Dump 3DS games from PC to FTP

### ISSUE THREAD

**Issue by MaitreAnonyme** [mtheall/ftpd#169]
Good morning,
Following the closure of the Nintendo eShop. I end up with a ton of 3DS/DS games stored on my physical 3DS. What I would like is to copy my 100GB of Games from my 3DS in .cia format from my PC (to have a copy in case of loss) in FTP or from another network protocol, without dumping in the format cia for each game manually then transfer it. This function exists on Switch with Homebrew DBI so why not on 3DS? Is it possible that FTPD or another Homebrew can dump a game remotely?
Good day.

**Comment by cheatfreak47** [comment]
the 3DS's network card is ridiculously slow, doing what you described even if it were added is practically infeasible

**Comment by mtheall** [comment]
This kind of thing will never be implemented by ftpd.
