### ISSUE TITLE
hostname support

### ISSUE THREAD

**Issue by BakedCrossiant** [mtheall/ftpd#188]
**Is your feature request related to a problem? Please describe.**
Due to dynamic IP assignment, FTPing (especially via Windows Explorer) can be cumbersome. Also hostnames make it easier to manage devices.

**Describe the solution you'd like**
Addition of a hostname service.

**Describe alternatives you've considered**
Static IP. However routers are quite finicky with dynamic IPs and the preference would be not to set one.

**Additional context**
N/A

**Comment by mtheall** [comment]
added in 7d8edde4b9354025f6171add9a1c6f6308ee56ab
