### ISSUE TITLE
Add support for wildcard when using ftp.exe on windows command prompt

### ISSUE THREAD

**Issue by julioSantosAlbarregas** [mtheall/ftpd#189]
**Is your feature request related to a problem? Please describe.**
I was trying to backup just the `.sav` files of all my games and I thought the best way to do that without taking out the micro sd card is to make a simple batch file with all the script to use `ftp.exe`, connect to the 3ds and then download all `.sav` files using `mget *.sav`, but sadly wildcards doesn't work and can't make them work in any way.

**Describe the solution you'd like**
use windows cmd to open a ftp connection using `ftp.exe` and get all files with different names but same extension (in my case `*.sav` files)

**Describe alternatives you've considered**
Have a list of all my games and download each corresponding save files one by one, which will result in a unnecessary large batch file and I'll have to update it eventually to add new games I've started to play, so a new `.sav` file is created, and a new name to add to the list of saves to backup.

**Additional context**

I have this simple batch file: `ftp -g -s:info.txt > logfile.txt`

`info.txt` is my task list that `ftp.exe` will run:

```
open 192.168.0.41 5000

cd /
lcd D:\Escritorio\Nuevacarpeta
bin
prompt
mget *.sav
disconnect
quit
```

but this is the `log.txt` with the result:

```
ftp> open 192.168.0.41 5000
Conectado a 192.168.0.41.
220 Hello!
200 OK
Usuario (192.168.0.41:(none)): 
230 OK
ftp> cd /
200 OK
ftp> bin
200 OK
ftp> prompt
Modo interactivo Desactivado .
ftp> mget *.sav
200 OK
450 No such file or directory
ftp> disconnect
221 Disconnecting
ftp> quit

```

I'm still able to download single files if I specify name and extension tho, that's why it may be possible to download every single `.sav` files one by one if I know the exact name of each of them.

**Comment by eku** [comment]
The RFCs that define FTP do not explicitly mention globbing; this means that FTP servers are not required to support globbing in order to be compliant.

**Comment by mtheall** [comment]
added in 623971c11a0c40d10046374ec2ff8183d359af9e
