### ISSUE TITLE
Re-add CIA support to latest 3DS version

### ISSUE THREAD

**Issue by GammaBoost** [mtheall/ftpd#191]
Accessing FTPD from the home menu was more convenient.

**Comment by Alcosmos** [comment]
This is probably gonna get closed ("DO NOT ASK ME TO SUPPORT CIA"), but the only mentions of this update ive seen are people complaining about the lack of a CIA. Nobody wants to go back to the Homebrew Launcher

**Comment by mtheall** [comment]
Why the hate on hbmenu? It's like a billion times faster to switch between apps than home menu

**Comment by pav1388** [comment]
> Why the hate on hbmenu? It's like a billion times faster to switch between apps than home menu

cia - first click on the icon to launch ftpd, second click on the start button to close app.

3dsx - first click on the icon to launch the HB launcher, twenty-three clicks to find the application among dozens of others, twelve-fourth click to launch ftpd, twenty-fifth click on the home button, twenty-sixth click on the X button to close app.

is it really faster? what is the problem with cia?

**Comment by FakeJacob** [comment]
i just built a .cia version
![FTPD_CIA](https://github.com/user-attachments/assets/3ae85c46-6650-457a-9cf6-e08b7739157e)
heres the qr code

**Comment by pav1388** [comment]
> i just built a .cia version !

ftpd_classic.cia by any chance?

**Comment by FakeJacob** [comment]
> > i just built a .cia version !
> 
> ftpd_classic.cia by any chance?

yeah

**Comment by FakeJacob** [comment]
> ftpd_classic.cia by any chance?

i could do that

**Comment by lemaximedu66** [comment]
He re added the CIA thanks god 🎉🎉🎉🎉🎉

**Comment by GammaBoost** [comment]
good work guys
