### ISSUE TITLE
NintendoDS Lite FTPD test results 

### ISSUE THREAD

**Issue by cotodevel** [mtheall/ftpd#192]
FTPD testing results:

Everything happened in a single session:

-a 2MB transfer file (PC->DS): Test successful
-moved it to another directory: Test successful
-a 10MB transfer file (PC->DS): Test successful
-same 10MB transfer file (DS->PC, same CRC32 checksum): Test successful
-a 188MB transfer file (PC->DS): (Failed at 91.3MB transfer, disconnected)

Expected result:
Over 100MB files transfers working.

Platform:
- System: Nintendo DS Lite + r4igold.cc 
- DS Lite firmware: v5
- Launch method: Stock kernel or [ToolchainGenericDS-multiboot](https://github.com/cotodevel/toolchaingenericds-multiboot)
- Type: .NDS DevkitARM binary
- Program Tested: https://github.com/mtheall/ftpd/releases/tag/v3.2.1
- Wireless Device: 802.11n router working as 802.11b and Open Key (no password whatsoever), but NintendoDS MAC whitelisted. Works fine during online gameplay tests or online homebrew in general.

Anyway, overall, this is the best DS FTP program by far.
Thanks!

**Comment by mtheall** [comment]
Just retry? It should resume

**Comment by cotodevel** [comment]
Never been fan of retry commands on FTP ?

Closing issue.
