### ISSUE TITLE
ftBrony doesn't react to the B button at all times

### ISSUE THREAD

**Issue by d0k3** [mtheall/ftpd#20]
It only reacts after additional FTP commands. In Windows Explorer, f.e. you have to push the B Button on the 3DS (seemingly nothing happens) -> refresh or change the folder in Windows Explorer (it fails in WIndows Explorer, but on the 3DS you get the "Push B to quit message") -> push B again to quit.

I think (I'm not sure) the reason is in the ftp_session_read_command(ftp_session_t *session) function, more specifically in the line saying:
rc = recv(session->cmd_fd, buffer, sizeof(buffer), 0);

No idea how to properly fix this yet, though.

**Comment by Perikiyo** [comment]
maybe force close connections from serverside killing the FTP server and re-opening?

**Comment by d0k3** [comment]
Well, if we knew where to check the buttons, force exiting would be easy. Problem now is, I have no idea where in the source code it hangs.

**Comment by PerikiyoXD** [comment]
A sec... 
line43@main.c

**Comment by d0k3** [comment]
Yeah, that's where it waits for the B button (that's actually after you teh B button was detected the first time). The question is, if it refuses to react to the B button in any way - where in the code is it?

**Comment by d0k3** [comment]
Just a quick note... While ftBrony 1.1 does in fact look a lot better than ftBrony 1.0 (I'm also pretty sure there are a lot under-the-hood changes), it will still not fix this issue.

**Comment by mtheall** [comment]
I finally narrowed this down to socExit() blocking. I'm not sure how to investigate further. ftBRONY will respond when the client drops its connection.

**Comment by d0k3** [comment]
Thanks for looking into this! I'm pretty sure force exit would be possible, but the (possible) consequences...? No idea. That issue doesn't happen with 'proper' FTP clients, btw, but almost everyone uses WIndows Explorer, I guess.

**Comment by mtheall** [comment]
I've seen it happen with several apps, such as ES File Explorer on my phone.

You should be able to hold L+R+DOWN+B to exit to hbmenu. That's finnicky though, I think it will leak open handles. I would also try closing Windows Explorer.

**Comment by d0k3** [comment]
No, closing it does not work. If you close it, you are forced to do the force close on 3DS. You need to (1) press B on 3DS, (2) F5 refresh in Explorer, (3) press B again on 3DS.

**Comment by deadair3210** [comment]
I have had it happen with Cyberduck as well, though not with the recent release.

**Comment by mtheall** [comment]
As far as I can tell, this is just a quirk of the SOC:U service. It's blocking on SOCU_Shutdown(). I tried setting linger options, as well as using recv() on the socket before doing close() (in case that was needed to ACK a client-side shutdown). Nothing seems to help at all. The best I can do for now is put a print message that says "Waiting for socExit()..."
