### ISSUE TITLE
Can't build via cygwin with devkitARM and libctru

### ISSUE THREAD

**Issue by ofry** [mtheall/ftpd#30]
I compiled devkitARM release 45 with libctru-0.6.0.

Next I tried to make build of ftpd:

Log:
https://dl.dropboxusercontent.com/u/97349870/ftpd-dff661c-build.log

**Comment by ofry** [comment]
With ctrulib 1.1.0:

https://dl.dropboxusercontent.com/u/97349870/ftpd-dff661c-build-ctrulib-1.1.0.log

**Comment by mtheall** [comment]
You need the latest development version of libctru

**Comment by ofry** [comment]
ok, will test it :)

**Comment by ofry** [comment]
Thanks. It compiles with dev version of libctru.

Please clarify the Readme :) Thanks for help.
