### ISSUE TITLE
Doesn't send 220

### ISSUE THREAD

**Issue by jtvjan** [mtheall/ftpd#31]
Normal servers send 220 after logging in to indicate that it it ready for the new client. As ftbrony doesn't send this after someone logs in some clients just throw an error and don't connect.

**Comment by mtheall** [comment]
Can you tell me specifically which command are you expecting a 220. Is it from USER or PASS, or something else?

**Comment by NasaGeek** [comment]
I had noticed it at https://github.com/mtheall/ftpd/blob/master/source/ftp.c#L957 previously, but you fixed that with https://github.com/mtheall/ftpd/commit/f7156e8ca903e073d8e255a1bca548df469a70b7. jtvjan might be referring to a different function, though.

**Comment by jtvjan** [comment]
@NasaGeek I should make it a habit to check for updates before opening issues. Updated and it works. I'm sorry…

**Comment by mtheall** [comment]
Okay yeah I think I ran into that problem when trying to use cURL.
