### ISSUE TITLE
Exit via B not possible while waiting for wifi

### ISSUE THREAD

**Issue by d0k3** [mtheall/ftpd#35]
What the title says. While ftpd is waiting for wifi, I can't exit via B. I instead get a red errormessage.

**Comment by mtheall** [comment]
What is the error message you get? Is your wifi unavailable or do you have the wifi switch turned off?

**Comment by d0k3** [comment]
The error message is:
ACU_GetWifiStatus returns 0xe0a09d2e
That wifi (the wifi access point in my home) is somewhat problematic. I think ftpd should allow me to exit while waiting for wifi regardless of what is the problem behind the wait for wifi is endless :).

**Comment by mtheall** [comment]
Are you using the latest code? That error should never print out, and you should be able to press B to exit that loop already. That should be working with 920cd96c.

**Comment by d0k3** [comment]
Well, to be honest, I didn't build myself but was using the latest binary release instead. I'll update then test again.

**Comment by d0k3** [comment]
Okay, tried to build myself and failed. DevKitARM and libctru is up to date. I'm getting tons of unknown type names, starting with SOCU_TCPTableEntry tcp_entries[32]. I know this is anotehr issue, and if you want me to I'll open a new one for that.

**Comment by mtheall** [comment]
You need the latest libctru, too. I don't mean the latest release, you need code from upstream. See https://github.com/smealum/ctrulib/commit/2b9dc3c8. If you don't want to use that, the latest version of ftpd/ftbrony you can use is 10d7ed62.

**Comment by m45t3r** [comment]
Here it is a version build from last commit from cia branch (14ccbac).

[ftpd.zip](https://github.com/mtheall/ftpd/files/113411/ftpd.zip)

**Comment by mtheall** [comment]
I can only test the 3dsx file you provided, and it worked as expected for me. It said "Waiting for wifi..." and I pressed B, then it said "Press B to exit" with no error message. Then pressing B exited to hbmenu.

**Comment by d0k3** [comment]
Sorry to keep you waiting. I tested the 3DSX, and it worked fine, so I'm closing this issue for now.

However, the CIA file crahed for me on each and every attempt (after being installed to the homemenu) @m45t3r might want to look into that.

**Comment by m45t3r** [comment]
It seems to work, somewhat. If you load ftpd right after booting 3DS, pressing B crashes the system (you can't even go back to home menu, needs to hold down power button). The "Press B to exit" message does not appear either, so the problem is in the code in `ftp.c`.. However, if you give sometime (like 30 seconds) before opening ftpd or pressing B button (you can even open another app), pressing B seems to work correctly.

Maybe this is related to issue #20? However this seems to be more serious since it crashes the system.

**Comment by m45t3r** [comment]
Commenting out lines 1597-1598 seems to fix out this issue. Maybe it is some problem with function `ftp_closesocket()`?

@d0k3, can you test this build below?

[ftpd.zip](https://github.com/mtheall/ftpd/files/116426/ftpd.zip)

**Comment by mtheall** [comment]
I don't see how that can help. If you press B, you will exit the function without reaching the code you commented out.

**Comment by mtheall** [comment]
This is probably due to calling socExit() when we haven't called socInit().

**Comment by mtheall** [comment]
Try wrapping lines [1604-1607](https://github.com/mtheall/ftpd/blob/master/source/ftp.c#L1604-L1607) in `if(SOCU_buffer != NULL)`.

**Comment by m45t3r** [comment]
@mtheall I already tried this, did not work.

**Comment by mtheall** [comment]
I don't think v3.0.0 branch suffers from this problem
