### ISSUE TITLE
Building as 3DS / CIA

### ISSUE THREAD

**Issue by d0k3** [mtheall/ftpd#36]
This is rather an enhancement than a bug, but would adding .CIA / .3DS build goals be possible? It has been done, f.e. in this fork of ftpd:
https://github.com/FloatingStar/FTP-GMX

It requires including a few additional binaries (bannertool, makerom, info.rsf). For the two executables - those could be included as submodules and compiled from source (so that it will still be platform independent).

I'd be willing to do the pull request for this if you are interested.

**Comment by m45t3r** [comment]
It is already done in issue #11, check [cia](https://github.com/mtheall/ftpd/tree/cia) branch for code. It uses Steveice10/buildtools, I made the icons and ripped off the sound from FBI.

Now, I don't know if @mtheall will merge cia branch in master someday. I hope so, it is difficult to maintain to separate branches.

**Comment by d0k3** [comment]
I've seen it, thank you. And it's platform indpendent, too. Will close this then, thank you!
