### ISSUE TITLE
Can't download files with >2Gb size

### ISSUE THREAD

**Issue by ofry** [mtheall/ftpd#38]
I can't download from my 3ds file with size more than 2147476592 bytes (it's near 2 Gb).

**Comment by ofry** [comment]
I use v2.1.

**Comment by profi200** [comment]
That should be a limitation of newlib. It only allows 32 bit offsets but the os supports bigger files. Fixing this would require switching to the native fs API.

**Comment by ofry** [comment]
Is it possible in FW < 9.2?

**Comment by profi200** [comment]
It is not a firmware limitation. It is a limitation of the fs API used in this app. I would wait and see what the author wants to do to fix it or if he wants to fix it at all.

**Comment by mtheall** [comment]
Looks like newlib was built with 32-bit offsets. I will try enabling 64-bit offsets and see if that fixes it.

**Comment by mtheall** [comment]
I was able to download a 2GB file without enabling 64-bit offsets. Maybe you had a different problem, or maybe your destination filesystem doesn't support large files?

**Comment by ofry** [comment]
Can you test smth with 2.1Gb file? I think 2Gb file will download normal, but 2Gb + some bytes will fail to download.

**Comment by mtheall** [comment]
I made a change in a92b041d but that actually might make the situation temporarily worse (printing a negative size). The next release of devkitARM and rebuilding libctru against that should make offsets to be 64-bit, and so you won't get negative sizes anymore. After that I would revisit this issue. I have an old 3DS and it took about 50 minutes to download the 2GB file.

**Comment by mtheall** [comment]
I'm trying again (with the old code) with a 2GB+1MB file.

**Comment by mtheall** [comment]
Okay the 2GB+1MB file worked as well. What client are you using?

**Comment by ofry** [comment]
FileZilla 3.15.0.

**Comment by ofry** [comment]
I checked some more...

Downloading of big files failing quite often :(

Sample log part:

REST 1363396
502 unavailable

**Comment by mtheall** [comment]
So have you been getting this error all along? Is this just a problem with the REST command?

**Comment by ofry** [comment]
Maybe. I use https://github.com/mtheall/ftpd/releases/tag/v2.1 this version of ftpd.

Can you make 2.2 release based on current commit? Thanks.

**Comment by mtheall** [comment]
I'm not going to make a v2.2 release until devkitARM/libctru are released with the code that I am using. In the meantime, try out this build:

[ftpd.3dsx.zip](https://github.com/mtheall/ftpd/files/119868/ftpd.3dsx.zip)

**Comment by ofry** [comment]
This version working fine :) Thanks.
