### ISSUE TITLE
Why does the ftpd connect to Nintendo servers?

### ISSUE THREAD

**Issue by EchoDev** [mtheall/ftpd#42]
Not really an issue, just curiosity:

On startup it seems to connect to ~2 Nintendo servers

52.27.236.3:443 and 69.25.139.139:443

Something related to the used libraries?

**Comment by yellows8** [comment]
That has nothing to with homebrew.

**Comment by EchoDev** [comment]
![scr_1_bottom](https://cloud.githubusercontent.com/assets/3149302/13939840/a571d0ea-efd8-11e5-9b5e-553e57e27bd8.png)

It probably monitors and outputs all traffic on the 3DS.

**Comment by mtheall** [comment]
Apparently the API that retrieves the table gets all TCP sockets, including those from other processes. Some of the system services must be holding open connections.

**Comment by DumbJoe** [comment]
oh yeah, i notice that too; but mine are different: 52.24.15.250:443 and 35.163.21.170:443
