### ISSUE TITLE
Makefile doesn't properly generate the .smdh while building as a .cia, resulting in a blank icon.

### ISSUE THREAD

**Issue by AileSc** [mtheall/ftpd#47]
Not a big issue, but a few folks in #cakey noticed if you attempt to build ftpd as a CIA, the icon isn't generated properly and results in the CIA having a blank square for an icon. The issue seems to be the smdh generation in Makefile.3ds being commented out: 

`#$(OUTPUT).smdh	:	$(APP_ICON)`
`#	@bannertool makesmdh -s "$(APP_TITLE)" -l "$(APP_DESCRIPTION)"  -p "$(APP_AUTHOR)" -i $(APP_ICON) -o $@`
`#	@echo "built ... $(notdir $@)"`

The icon was generated correctly when those lines were un-commented out.

**Comment by mtheall** [comment]
I didn't want to have a dependency on bannertool, since I didn't even have it myself. There is already a rule in 3ds_rules that uses smdh_tool included with devkitARM, so maybe this should be fixed there.

**Comment by AileSc** [comment]
Okay, so the issue ended up being smdh_tool not setting some Home Menu-specific flags properly, but the latest version of smdh_tool has already fixed this, so looks like there's no need to rely on bannertool after all. Am gonna close this.

**Comment by fincs** [comment]
smdhtool [is already fixed](https://github.com/devkitPro/3dstools/commit/e5ccb1d7a6090fd1cd235ce8589492ef597f9eef), currently waiting for inclusion in the next version of devkitARM.
