### ISSUE TITLE
Needs a few important things.

### ISSUE THREAD

**Issue by Shadowehh** [mtheall/ftpd#53]
This really needs a secure connection and a password that is optional and changeable to connect to it safely.

**Comment by mtheall** [comment]
There is no known way to be the "server" side using the SSL:C service, so I would need to use a third-party SSL library which means all crypto is done by the CPU. This will make it even WAY slower than it already is.

Without encryption, password protection is moot. Anyone can sniff your traffic and get your password.

The only viable solution is by using the third-party SSL library on the command channel only. It's much too expensive to do it on the data channel, and no client is going to understand some custom protocol to turn off crypto on the command channel after authentication is complete.

**Comment by Shadowehh** [comment]
I don't see it slow, it goes quite fast probably due to me having a N3DS. Also this might help you out due to it being lightweight, open-source, fully-cross platform and CPU efficient. If this does not help you then you could use it for some other project. :P
http://www.matrixssl.org/
