### ISSUE TITLE
Press HOME button cannot exit

### ISSUE THREAD

**Issue by liangziqi124** [mtheall/ftpd#54]
At any moment I press B then it shows "Press the Home Button to exit", no button functions any more so I need to hard shutdown the device

using ftpd.cia via Luma3DSv6.1.1
ftpd v2.2-17f1036c
JPN 3DSL sys v11.0 (arm9ed)

**Comment by mtheall** [comment]
So you mean pressing the home button doesn't suspend the app?

**Comment by liangziqi124** [comment]
Exactly

**Comment by mtheall** [comment]
Sounds like aptMainLoop() is always returning true. Can you modify the code to print out the value of aptIsCrippled() after the print for "Press the Home Button" message?

**Comment by liangziqi124** [comment]
Sorry but I haven't learnt make 3ds program yet :(
I don't know if just removing the line 109 and 110 (console_print and while(aptMainLoop())) will work? The app would close while receive a B (I'm not sure as I don't even know what console_render() dose)

**Comment by JumperGerald** [comment]
Is your 3ds an o3ds or a n3ds?

**Comment by JumperGerald** [comment]
I tested this build with no issues on:
JPN N3DS w/ a9lh > Luma 6.1.1

**Comment by liangziqi124** [comment]
O3DS

**Comment by liangziqi124** [comment]
Sorry guys, I have just tested for some times but I failed to "re-encounter" the error I met before. I've always been using DOS ftp command to send/get/delete files on 3DS. I tested all those actions but no errors occurred.

**Comment by mtheall** [comment]
Okay, I will close this issue. If you run into it again just let me know and we can reopen it.
