### ISSUE TITLE
Frozen console when closing the lid

### ISSUE THREAD

**Issue by alvgalrus** [mtheall/ftpd#56]
Console: N3DS 11.1
Version: 2.2 CIA

When I closed the console, screen went black and transfer stopped. When opening the lid, screen is off and the console is frozen.

**Comment by mtheall** [comment]
Don't close the lid. I don't think we can support sleep mode; it turns off the wifi. I don't think we can disable sleep mode either. Press Start to turn off the backlight.

**Comment by mtheall** [comment]
Apparently support to disable sleep mode was added recently to libctru. I'll give it a whirl and get back to you.

**Comment by EmuAGR** [comment]
I've just tried and Start didn't turn off the backlight. It seems that when I close the lid, WiFi disconnects, and then reconnects when I open it, as expected. But doing so during transfer freezes de console.

**Comment by mtheall** [comment]
Did you try the latest build as linked in the README.md?

**Comment by EmuAGR** [comment]
ftpd v2.2-6d35bc07
The 7 latest commits weren't built into the release build yet: https://github.com/mtheall/ftpd/compare/v2.2...master

**Comment by mtheall** [comment]
The link on the README.md is a post-commit build. It will always be the latest version.

**Comment by mtheall** [comment]
Using aptSetSleepAllowed(false) does not seem to help.
