### ISSUE TITLE
Important things needed

### ISSUE THREAD

**Issue by Shadowehh** [mtheall/ftpd#58]
Yes, I do know I have posted this before and you should know too, but I have found something that is not too expensive on the resources side of the 3DS. **This will allow FTP over TLS on the 3DS** without using way too much resources if you go to and use matrixssl , as I read it says that matrixssl is very lightweight meaning that you know, it would not use so much resources to create a FTP over TLS connection. **Just go to _matrixssl.org_** and you will see it. **You should also enable a password** (which should be optional too) that can be changed so nobody can accidentally or purposefully access the 3DS system and mess up some files in it. I ended up finding matrixssl just by doing a tiny bit of research, but I guess this might help or not.

**Comment by mtheall** [comment]
I may get around to this someday if I can get matrixssl working. I do have a copy of this working with OpenSSL for the Linux version.
