### ISSUE TITLE
Code not compiling 

### ISSUE THREAD

**Issue by evakimox** [mtheall/ftpd#60]
We tried to make on Linux but got error report saying a lot of variables not declared. . . I saw there's an update post on devkitARM. . Not on 3ds so I am not very sure if the not compiling issue is generated by that.
What I do is just go to the folder where I put every code and makefiles. Then I type make
Or if anyone can tell me if it still compile on Windows? And how about after installing the devkitARM last update on Nov 16

**Comment by rweichler** [comment]
post the logs.

**Comment by Rangnarok123** [comment]
I have some error while compiling too. Here is my log

`

console.c
arm-none-eabi-gcc -MMD -MP -MF /d/Project/ftpd-master/build/console.d -g -Wall -
O3 -mword-relocations -fomit-frame-pointer -ffunction-sections -march=armv6k -mt
une=mpcore -mfloat-abi=hard -mtp=soft -DSTATUS_STRING="\"ftpd v2.2.0\"" -I/d/Pro
ject/ftpd-master/include -I/D/devkitPro/libctru/include -I/d/Project/ftpd-master
/build -DARM11 -D_3DS -c /d/Project/ftpd-master/source/console.c -o console.o
d:/Project/ftpd-master/source/console.c: In function 'print_tcp_table':
d:/Project/ftpd-master/source/console.c:73:10: error: unknown type name 'SOCU_TC
PTableEntry'
   static SOCU_TCPTableEntry tcp_entries[32];
          ^
d:/Project/ftpd-master/source/console.c:81:8: warning: implicit declaration of f
unction 'SOCU_GetNetworkOpt' [-Wimplicit-function-declaration]
   rc = SOCU_GetNetworkOpt(SOL_CONFIG, NETOPT_TCP_TABLE, tcp_entries, &optlen);
        ^
d:/Project/ftpd-master/source/console.c:81:27: error: 'SOL_CONFIG' undeclared (f
irst use in this function)
   rc = SOCU_GetNetworkOpt(SOL_CONFIG, NETOPT_TCP_TABLE, tcp_entries, &optlen);
                           ^
d:/Project/ftpd-master/source/console.c:81:27: note: each undeclared identifier
is reported only once for each function it appears in
d:/Project/ftpd-master/source/console.c:81:39: error: 'NETOPT_TCP_TABLE' undecla
red (first use in this function)
   rc = SOCU_GetNetworkOpt(SOL_CONFIG, NETOPT_TCP_TABLE, tcp_entries, &optlen);
                                       ^
d:/Project/ftpd-master/source/console.c:86:50: error: 'SOCU_TCPTableEntry' undec
lared (first use in this function)
     for(i = 0; lines < 30 && i < optlen / sizeof(SOCU_TCPTableEntry); ++i)
                                                  ^
d:/Project/ftpd-master/source/console.c:88:27: error: 'entry' undeclared (first
use in this function)
       SOCU_TCPTableEntry *entry  = &tcp_entries[i];
                           ^
d:/Project/ftpd-master/source/console.c:95:14: error: 'TCP_STATE_CLOSED' undecla
red (first use in this function)
         case TCP_STATE_CLOSED:
              ^
d:/Project/ftpd-master/source/console.c:100:14: error: 'TCP_STATE_LISTEN' undecl
ared (first use in this function)
         case TCP_STATE_LISTEN:
              ^
d:/Project/ftpd-master/source/console.c:105:14: error: 'TCP_STATE_ESTABLISHED' u
ndeclared (first use in this function)
         case TCP_STATE_ESTABLISHED:
              ^
d:/Project/ftpd-master/source/console.c:109:14: error: 'TCP_STATE_FINWAIT1' unde
clared (first use in this function)
         case TCP_STATE_FINWAIT1:
              ^
d:/Project/ftpd-master/source/console.c:113:14: error: 'TCP_STATE_FINWAIT2' unde
clared (first use in this function)
         case TCP_STATE_FINWAIT2:
              ^
d:/Project/ftpd-master/source/console.c:117:14: error: 'TCP_STATE_CLOSE_WAIT' un
declared (first use in this function)
         case TCP_STATE_CLOSE_WAIT:
              ^
d:/Project/ftpd-master/source/console.c:121:14: error: 'TCP_STATE_LAST_ACK' unde
clared (first use in this function)
         case TCP_STATE_LAST_ACK:
              ^
d:/Project/ftpd-master/source/console.c:125:14: error: 'TCP_STATE_TIME_WAIT' und
eclared (first use in this function)
         case TCP_STATE_TIME_WAIT:
              ^
make[2]: *** [console.o] Error 1
make[1]: *** [3dsx] Error 2
make[1]: Leaving directory `/d/Project/ftpd-master'
make: *** [3dsx] Error 2
`

**Comment by evakimox** [comment]
I have same kind of problems has rangnarok123, only difference is that I was on Linux.

**Comment by evakimox** [comment]
https://www.reddit.com/r/3dshacks/comments/5f9bbe/unable_to_compile_ftbrony_ftpd_or_ftpgmxfloating/
My team post this question and analogMan end up make this work. Thanks to him, it is the last answer and I think I should share this solve with Rangnarok123

**Comment by mtheall** [comment]
Compile with head of libctru/master. The newest libctru release does not have the required functionality. It will be available with the next release.
