### ISSUE TITLE
Can't delete from Nintendo 3DS folder?

### ISSUE THREAD

**Issue by FayneAldan** [mtheall/ftpd#62]
I tried to delete my home menu extdata folder in preparation for downgrading, but it gave me the error:
`unlink: 2 No such file or directory`

**Comment by mtheall** [comment]
`unlink` (DELE) is for files. Use `rmdir` (RMD) for directories.

**Comment by FayneAldan** [comment]
You need to delete the files inside the directory first, do you not?

**Comment by mtheall** [comment]
Yes, but that would give you a "directory not empty" error if you didn't. What client are you using and in what way are you trying to delete the extdata folder?

**Comment by FayneAldan** [comment]
I'm using WinSCP and I clicked delete on the folder. The `unlink` error is on the 3DS while WinSCP simply says `failed to delete file`

**Comment by mtheall** [comment]
Does it specify which file failed to be deleted? Which command is displayed on the 3DS preceding the failure message?

**Comment by FayneAldan** [comment]
```
DELE /Nintendo 3DS/eea70349f98b0510a4211b6e196120b2/7a3200c6478002485355313600035344/extdata/00000000/0000008f/00000000/00000001
unlink: 2 No such file or directory
550 failed to delete file
```

**Comment by mtheall** [comment]
Can you verify that the file actually exists?

**Comment by FayneAldan** [comment]
I'd assume it's there, considering that WinSCP says it's there.

**Comment by mtheall** [comment]
Can you try to delete just that file specifically?

**Comment by FayneAldan** [comment]
same error

**Comment by mtheall** [comment]
Are you able to download the file?

**Comment by FayneAldan** [comment]
No, but I can't really try it right now. Could the problem be that it's in the Nintendo 3DS folder? Because other HB apps aren't able to delete the files either.

**Comment by mtheall** [comment]
I'm not sure. I don't remember specifically trying to delete anything from there. You might want to fsck your sd card and make sure nothing is corrupt.

**Comment by RubberBrony** [comment]
It's definitely because it's in the Nintendo 3DS folder. 3DS games and applications aren't allowed to directly write to HOME Menu extdata. The things that do write to HOME Menu extdata do so in a different way; Cthulu ([Cache Tool](https://github.com/Ryuzaki-MrL/CacheTool)), for example, runs in extended memory mode so writes to HOME Menu data isn't blocked.

I know this is an old issue, but it's still "open" so I figured input was needed.
