### ISSUE TITLE
Doesn't always connect.

### ISSUE THREAD

**Issue by alpharou** [mtheall/ftpd#66]
IDK why, but old versions of FTPD don't give me this problem. version 1.0 of FTBrony was snappier (and had a really unique interface), I clicked connect, it went ahead and did that. Now... I have to wait like 20 secs, even 30, when the FTP client says timeout... Why does this happen? And does it happen to me only? Filezilla keeps telling me waiting for welcome message, and WinSCP just spits up timeouts.

**Comment by mtheall** [comment]
Can you bisect the problem? Is there some revision that works flawlessly for you but then the next revision has problems?

**Comment by Alpharou** [comment]
I thought about doing that... but the other releases files aren't cias and I don't know how to install those... they're something like .xy... strange. I could install the version 1.0 of FtBrony through TitleDB.

**Comment by Alpharou** [comment]
And, extra info, when the connection fails, the 3ds spits this:
- accepted connection from 192.168.1.15(my desktop local IP)   :59821 (This is strange, I don't know how FTP really works, but every time it tries, it's a random port... Like if it was trying to use higher ones when the one it uses fails...)
- 220 Hello!
- Closing connection to 192.168 etc etc.

**Comment by jacobmartin03** [comment]
I'm having the same issue right now. It's very slow and It stops the connection at each operations

**Comment by DumbJoe** [comment]
ditto even with the latest v2.3...

**Comment by DumbJoe** [comment]
...it's actually funny how it can easily connect to external IPs no problems, but when you try to connect to your own server locally, it doesn't always work....
