### ISSUE TITLE
Strange IP address

### ISSUE THREAD

**Issue by shahanshah3** [mtheall/ftpd#67]
This isn't necessarily a problem with ftpd, but when I launch ftpd, my 3DS gets assigned an unusual IP address, and I can no longer connect to it using filezilla. My IP address was 10.0.1.7, has something similar occurred to anyone else?

**Comment by fincs** [comment]
10.x.x.x is a perfectly valid local IP address.

**Comment by shahanshah3** [comment]
Hmm, very well. It worked again after I randomly changed the connection settings, so it's alright.
