### ISSUE TITLE
Large Folders Display Empty on Client

### ISSUE THREAD

**Issue by SpookySpleen** [mtheall/ftpd#68]
Folders with a large total file size (i.e. multiple cart dumps) can be opened on the client, but show nothing inside of them.  Total file size in the folder when this happened was a little over 2.2 GB, and individual file sizes ranged from 256 MB to 1 GB.  Files in this folder showed up fine on the client when the total size in the folder was ~1.2 GB.  I don't know enough about FTP to know if this is an inherent limitation or not, or if it is related to issue #38, which covered large individual files.

Anyway, I thought I should let you know just in case you didn't already.  Thank you for a great program!

**Comment by gingerbeardman** [comment]
Could it be that it was taking a very long time to show the directory? See https://github.com/mtheall/ftpd/issues/71

**Comment by mtheall** [comment]
It's possible. The amount of time to get a file's mtime looks like it depends on its position in the directory. The further down it is, the longer it takes to get, which sounds like ninty's fs driver has to traverse the entire directory listing to get to that file's timestamp. I'm not sure if file sizes within the directory have any bearing on this timing.

**Comment by gingerbeardman** [comment]
I noticed that GodMode9 is very fast at listing directories.
RetroArch is also fast.

CTRXplorer, by the author of GodMode9, on the other hand is very slow at listing directories.

I've no idea about their different approaches, but I thought it was worth mentioning.

**Comment by mtheall** [comment]
Do GodMode9 and RetroArch grab timestamps? Does CTRXplorer?

**Comment by gingerbeardman** [comment]
I'll look into it

**Comment by mtheall** [comment]
Option to disable mtime on 3DS added in v3.0.0 branch
