### ISSUE TITLE
Large file transfers time out after a long period of time.

### ISSUE THREAD

**Issue by DevShadd** [mtheall/ftpd#69]
I currently use FTPD for transferring things such as CIA files and ROMFS files, but some of the files are large and then after a long period of time, FTPD decides to close the connection to the client that is in the middle of a large transfer. This doesn't happen when you transfer lots of amounts of small files. I managed to stop it from timing out by opening an unopened folder to request some file data from the folders to prevent it from closing the connection. This gets very annoying after a while.

*BTW, I can't use the SD card on my PC because it says that the file format is unrecognized, so my only option is FTPD, especially because I have used more than 8GB of storage on my SD card.*

**Comment by mtheall** [comment]
Which ftp client are you using? About how long before timeout?

**Comment by DevShadd** [comment]
The only FTP server I could find is FileZilla. I think it times out about somewhere between 10-15 minutes, although it is the 3DS that closes the connection to it randomly. The 3DS doesn't even say why, but all it says Connection Closed to [the client address].

**Comment by onmyouji** [comment]
Have you tried using different PC? Or maybe different router.

It's also possible that your PC or router causes the problem.

**Comment by mtheall** [comment]
Try https://mtheall.com/~mtheall/ftpd_debug.3dsx (or .cia). When the problems happens, use a non-debug ftpd to retrieve the log file and send it to me.

**Comment by mtheall** [comment]
Make sure you stop the server by pressing B before exiting or you might not have a complete log.

**Comment by DevShadd** [comment]
I couldn't manage to get it to spit out the error. I managed to also transfer a 2GB file without it timing out.

**Comment by mtheall** [comment]
If it happens again and you can log it, reopen the issue.

**Comment by DumbJoe** [comment]
> 
> 
> Try [https://mtheall.com/~mtheall/ftpd_debug.3dsx](https://mtheall.com/%7Emtheall/ftpd_debug.3dsx) (or .cia). When the problem happens, use a non-debug ftpd to retrieve the log file (/ftpd.log on the SD card) and send it to me.

Is there a debug version for the latest?

**Comment by james-d-elliott** [comment]
If you are comfortable compiling all you need is the ENABLE_LOGGING compile flag from memory.

**Comment by DumbJoe** [comment]
> 
> 
> If you are comfortable compiling all you need is the ENABLE_LOGGING compile flag from memory.

How do I compile and where do I put that flag...?
