### ISSUE TITLE
Slow directory listing

### ISSUE THREAD

**Issue by gingerbeardman** [mtheall/ftpd#71]
Is there anything that could speed this up?

a less verbose listing?

use of NLST?

MLSD? https://github.com/mtheall/ftpd/issues/70

**Comment by mtheall** [comment]
The slow listing is solely due to grabbing each file's timestamp. There's no possible way to speed up getting the timestamps.

NLST is faster but most clients are going to just use LIST. MLSD will have the same problem if we provide the modify fact.

**Comment by gingerbeardman** [comment]
is there any way to list without timestamps?

**Comment by mtheall** [comment]
For now you will have to comment out the part in `list_transfer` that calls `sdmc_getmtime()`. The timestamp is critical for clients that support the operation "overwrite if newer" when copying trees. All FTP servers that I know about send the timestamp in their `LIST` output.

The best you can hope for me to do is add a `SITE` command that changes the `LIST` output.

**Comment by mtheall** [comment]
`MLSD` and `MLST` implemented via 7b1176d3 and d00b1a8c.

**Comment by gingerbeardman** [comment]
Thanks!

**Comment by mtheall** [comment]
In FileZilla, I would send the custom command `OPTS MLST Type;Size;Perm;UNIX.mode;`. This will prevent the server from fathering/sending timestamps on directory listings, which should dramatically speed up larger listings.
