### ISSUE TITLE
ftpd does not return supported commands

### ISSUE THREAD

**Issue by rctgamer3** [mtheall/ftpd#72]
```220 Hello!
User anonymous
230 OK
OPTS utf8 on
200 OK
SYST
215 UNIX Type: L8
502 Invalid command "sitehelp"
```
https://en.wikipedia.org/wiki/List_of_FTP_commands
Inspect `SITE HELP` output for complete list of supported commands.

**Comment by mtheall** [comment]
Commands are listed via the `HELP` command. I can add the output to `SITE HELP`.

**Comment by mtheall** [comment]
As far as I can tell, `SITE HELP` only lists the commands available via `SITE`. Since we don't have any `SITE` commands, I won't implement this. Use `HELP` to  view available commands.
