### ISSUE TITLE
Latest commit doesn't show directories

### ISSUE THREAD

**Issue by urherenow** [mtheall/ftpd#73]
Not sure which commit changed things but I just built ftpd with a fresh clone and all directories show up as files that can't be downloaded. I use filezilla.

**Comment by mtheall** [comment]
Can you get FileZilla to show the results it gets for the MLST and MLSD commands?

**Comment by urherenow** [comment]
not sure how... but just reinstalled 6d35bc07 and it works fine, so it's definitely something with the newer commits.

I'll play around a few minutes to see if I can find what you're asking.

**Comment by urherenow** [comment]
MLST
250-Status
UNIX.mode=0777;/
250 End

MLSD
503 Bad Sequence of commands

**Comment by urherenow** [comment]
Interesting... Latest release works on WinSCP as well, but also chokes on latest commit with:

Unexpected directory listing line 
'CIAngel.cia///1392064/0/0/1494/45/87/22/0/1/1/1'.
Invalid argument to date encode [1494-45-87]

**Comment by urherenow** [comment]
Done with that. Left with this on WinSCP (FileZilla still doesn't work):

Unexpected directory listing line 'System Volume Information///0/1/0/1512/86/68/24/0/1/1/1'.
Invalid argument to date encode [1512-86-68]

Just to make sure my Ubuntu bash on Windows wasn't causing an issue, I tried a build from Windows command line as well.

**Comment by mtheall** [comment]
MLSD response goes over the data connection, so it requires a PASV or PORT to precede it.

**Comment by urherenow** [comment]
Sorry, I'm still having no luck. 2 different FTP clients. Which client are you using? Either way, the last official release works.

**Comment by mtheall** [comment]
Fixed with d00b1a8

**Comment by urherenow** [comment]
I know this is closed, but I wanted to let you know that I've returned home from a vacation, and did a fresh build. Not only did you fix it, but it feels a lot more snappy than the last official release!

I'm not sure why you don't micro-bump the version and make the current source official.

**Comment by mtheall** [comment]
> I'm not sure why you don't micro-bump the version and make the current source official.

I'm in the middle of a major refactor, but it's uncertain whether I'll ever finish it :3
