### ISSUE TITLE
No FTP over TLS?

### ISSUE THREAD

**Issue by DumbJoe** [mtheall/ftpd#77]
A more secure and error free way of transferring files wirelessly.....so if a file transfers over corrupted, it will re-do the transfer or at least redownload the corrupted bits, whereas without TLS, you wouldn't know if the file is corrupted or not on transfer until you try out the file in whatever program it is you need it for and it turns out to be a dud....requiring you to re-transfer the file again...

**Comment by WinterMute** [comment]
That's not what TLS does ...

**Comment by DumbJoe** [comment]
> 
> 
> TLS provides data integrity in that it prevents others from tampering with the connection. HTTPS, for example, uses TLS.
> 
> TCP already handles checksums, which is meant to prevent corruption. Most of the time this is enough, but you can still get data corruption which "looks" like it's valid.
> 
> FTP doesn't have any error correction in the application layer, so there's nothing that can be done on that end.

ok so what do you use to ensure error correction via ftp if it isn't ftp over tls, hmmm?

**Comment by james-d-elliott** [comment]
Your only option is to independently check the file with something like MD5 checksums. As stated above TLS doesn't do anything to solve this; the data integrity it's talking about is preventing a MITM attacker from altering the data between the FTP client and the FTP server without any knowledge.

If you have data you wish to put on your 3DS and you want to ensure it's transferred properly it's better to use an SD card reader/writer.

**Comment by DumbJoe** [comment]
> 
> 
> Your only option is to independently check the file with something like MD5 checksums. As stated above TLS doesn't do anything to solve this; the data integrity it's talking about is preventing a MITM attacker from altering the data between the FTP client and the FTP server without any knowledge.
> 
> If you have data you wish to put on your 3DS and you want to ensure it's transferred properly it's better to use an SD card reader/writer... plus it's much faster.

Soo I googled a bit here and there and found this page: https://ask.metafilter.com/12120/Why-do-you-get-corrupt-FTP-transfers-if-its-over-TCPIP so someone suggest we should use Kermit or  X/Y/Zmodem protocols which has error correction feature that ftp doesn't. Apparently SFTP also have error correction: https://www.flashfxp.com/forum/13335/p71947-post5.html even if it's similar to FTP over TLS.....unless that guy is wrong and or the guy who suggests Kermit and XYZ modem protocols too ....

Isn't there a FTP program that auto checks the integrity of the file after each transfer for me instead of me loading up a hashing tool and checking them both individually manually? 

Mmm, I suppose it may be faster but for convenience of not needing to take out the SD card......or what if you don't have an SD card reader...?

**Comment by james-d-elliott** [comment]
https://serverfault.com/questions/414525/moving-a-13-gig-file-over-sftp-md5sum-fails

**Comment by mtheall** [comment]
At some point I may attempt creating an rsync server

**Comment by DumbJoe** [comment]
...so we should all be using SCP (Secure Copy, via SSH)?

I take it rsync uses SCP?

**Comment by DumbJoe** [comment]
So I heard Microsoft finally bought out github: https://www.pcgamer.com/microsoft-completes-github-acquisition-promises-not-to-screw-things-up/

...and the first thing they do is remove the quote function that allows quoting specific users to their respective reply and not using the generic quote.....or and edit my own post function....or is it just me?

**Comment by yellows8** [comment]
@DumbJoe "..." button

**Comment by DumbJoe** [comment]
Yes: https://i.imgur.com/Ra3E8qg.png

**Comment by akizuha** [comment]
can not find anywhere to set a username & password
and a sftp mode would be great

**Comment by mtheall** [comment]
User/Pass added in v3.0.0 branch. TLS does not ensure file integrity.
