### ISSUE TITLE
Maybe add a WiFi signal rate and or battery rate?

### ISSUE THREAD

**Issue by DumbJoe** [mtheall/ftpd#78]
For example using a 5 bar system, all five bars coloured in = perfect as can be signal, 4 out of 5 = 80% signal strength, 3 out 5 = 60% signal strength, 2 out of 5 = 40% signal strength, 1 out of 5 = 20% signal strength and no bars coloured = WiFi turned off or no WiFi is found because the signal is so weak that it can't even connect.

Or could use a more detailed method using percentages from 0% to 100% rather than bars of signal which would work too.

And assuming you will be transferring over large amounts of files or a large file, a battery indicator would be nice, either a detailed percentage 0 to 100%, estimated remaining time left of battery or a bar method works too.

**Comment by mtheall** [comment]
v3.0.0 branch
