### ISSUE TITLE
New banner and icon for 3ds

### ISSUE THREAD

**Issue by vulpes-vulpeos** [mtheall/ftpd#81]
Made banner and icon for 3ds. Icon mimics native microsd management (didn`t have better idea).
You can use them freely.

![ftpd banner](https://user-images.githubusercontent.com/40931454/47931402-5fb78e00-ded7-11e8-85e2-aebed7f03673.png)
![ftpd icon](https://user-images.githubusercontent.com/40931454/47931403-60502480-ded7-11e8-87dd-8a5548910117.png)

**Comment by CVFireDragon** [comment]
hey, do you mind making a switch version of this? nice job making this!

**Comment by vulpes-vulpeos** [comment]
> hey, do you mind making a switch version of this? nice job making this!
No problem, I`ll make it.

**Comment by vulpes-vulpeos** [comment]
![ftpd_switch](https://user-images.githubusercontent.com/40931454/48849992-342a1400-edb0-11e8-92ff-1a67d71b99bf.jpg)

**Comment by CVFireDragon** [comment]
thanks a lot!

**Comment by CVFireDragon** [comment]
do you mind if  I put up a pull request to change the old pics to these better ones?

**Comment by vulpes-vulpeos** [comment]
I don't mind, you can do it. Anyway I don't know how to do it myself :)
