### ISSUE TITLE
START - Screen stays black

### ISSUE THREAD

**Issue by MZ-4** [mtheall/ftpd#82]
Screen gets black when pressing START - that's cool!
But it stays black if you accidentally quit ftpd by 2xB. ;-)
A short standby (closing+opening 3DS) switched screen on again.
Perhaps ftpd should switch screen on again when exiting (2xB).

**Comment by Joelgp83** [comment]
Just ran into this, only instead of exiting, I had left the screen off for appoximately 3-5 minutes then discovered the screen is not coming back on when pressing start.  Also, can confirm that screen stays black after exiting, and can be brought back by opening + closing 3ds system.

**Comment by mtheall** [comment]
The "screen off" feature has not been ported to the v3.0.0 branch. I may try to add it back in the future, and make sure to take care of this issue.

**Comment by mtheall** [comment]
"screen off" is now in v3.0.0 branch. Restores backlight on exit.
