### ISSUE TITLE
Read only on Switch 6.01?

### ISSUE THREAD

**Issue by Dendim0n** [mtheall/ftpd#83]
Can't write....

**Comment by WinterMute** [comment]
Did you check write protect tab on your SD card?

**Comment by mtheall** [comment]
MicroSD cards don't have that

**Comment by WinterMute** [comment]
oops, switch, sorry.

This works fine for me. Are there any particular files or folders this happens with? Are any files or folders write protected?

**Comment by Dendim0n** [comment]
> oops, switch, sorry.
> 
> This works fine for me. Are there any particular files or folders this happens with? Are any files or folders write protected?

Cyberduck is fine, and macOS's Finder is read-only..

**Comment by WinterMute** [comment]
If you solved your issue it would be good to specify what the problem was so there's a solution for anyone else who encounters it.

**Comment by Butterscotch96** [comment]
> If you solved your issue it would be good to specify what the problem was so there's a solution for anyone else who encounters it.

I am "anyone else" in this situation.

**Comment by Masamune3210** [comment]
Finder's FTP is read-only, that's why they said that Cyberduck worked. In reality, literally anything that isn't Finder will work, Apple just decided to gimp Finder....for some reason I'm sure only they can logic out

**Comment by viktorashi** [comment]
> > oops, switch, sorry.
> > This works fine for me. Are there any particular files or folders this happens with? Are any files or folders write protected?
> 
> Cyberduck is fine, and macOS's Finder is read-only..

THANKS A OMG I LOVE READING GITHUB ISSUES
