### ISSUE TITLE
timestamp problem

### ISSUE THREAD

**Issue by akizuha** [mtheall/ftpd#85]
1. the ftp client get wrong timestamp for all files
2. MFMT command totally not working

**Comment by akizuha** [comment]
![2018-12-19_160717](https://user-images.githubusercontent.com/45957847/50207171-ac342b80-03a8-11e9-8250-3acc43ed35a6.png)

Left side is ftp, right side is local folder.
The file was copied to cd card via card reader.
So the left side time is absolutely wrong.

Don’t know how to add MFMT support, that’s why I’m asking.

**Comment by mtheall** [comment]
Looks like exactly an 8-hour time difference. Are you sure you don't have different time zone settings between your pc and your 3DS?

**Comment by akizuha** [comment]
Is there any time zone settings is 3DS?

**Comment by CVFireDragon** [comment]
for me, the times on the switch don't show up, its like 1960 or something

**Comment by yellows8** [comment]
@CVFireDragon System-version (probably) too old.

**Comment by CVFireDragon** [comment]
I'm on 6.0 lol

**Comment by yellows8** [comment]
Last ftpd release was before libnx supported file-timestamps.

**Comment by mtheall** [comment]
As far as I can tell, the 3DS and Switch don't have native APIs to be able to support the MFMT command. Neither do any of the devoptabs shipped with libnx or libctru.

ftpd v3.0.0 branch is using localtime(3) so it should be giving a local timestamp.
