### ISSUE TITLE
No online clients will connect??

### ISSUE THREAD

**Issue by kokichioumalovesme** [mtheall/ftpd#87]
Hi. The only computer I currently own is a school-locked-down chromebook, so I cannot download any FTP clients such as filezilla. I have googled "online ftp client" and tried every single website on the front page. I am entering my IP address under server name/host name and entering anonymous login. I enter 5000 for the port. Everything is right, but none of them will even start to connect. I've tried literally 10 websites. Is there something I'm doing wrong? Please help, if I have to edit my SD card I have to do it at school and it's a pain.

**Comment by legoj15** [comment]
Online FTP clients likely only connect to online FTP servers, so that's probably why they're not working, since the 3DS FTP server is local (unless you port forward, a practical impossibility at school).

**Comment by kokichioumalovesme** [comment]
Ah, I see. Thank you. I guess I’ll close this since that answers my question. Again, thank you
