### ISSUE TITLE
MiXplorer FTP client includes current directory as child directory with ftpd 3DS.

### ISSUE THREAD

**Issue by vaguerant** [mtheall/ftpd#88]
MiXplorer is a file explorer app for Android which includes FTP support among other things. It's very possible this is a MiXplorer issue rather than an ftpd one, but the issue only appeared when I updated ftpd to version 2.3.

Since that update, every directory opened in MiXplorer also reports a child directory that is simply itself. e.g. In the root directory, I also have a "directory" called `192.168.1.103`. In `/3ds`, I have a "directory" called `3ds`, in `/3ds/data`, I have a "directory" called `data`.

If I open one of these duplicate directories from the MiXplorer UI, I get a generic "Invalid Argument" error on the MiXplorer side and the following on the 3DS side:
```
CWD /3ds/data/data
stat '/3ds/data/data': 2 No such file or directory

550 unavailable
closing connection to 192.168.1.164:55927
stop listening on 192.168.1.103:5015
accepted connection from 192.168.1.164:39847
220 Hello!
USER anonymous
230 OK
FEAT
221-
 MDTM
 MLST Type*;Size*;Modify*;Perm*;UNIX.mode;
 PASV
 SIZE
 TVFS
 UTF8

211 End
OPTS UTF8 ON
200 OK
CWD /3ds/data//3ds
553 Invalid argument
closing connection to 192.168.1.164:39847
```
I then have to hit Back three times on MiXplorer to return to the directory I was initially in: I won't quote the entire ftpd log, but MiXplorer attempts the following:

1st Back press: `CWD /3ds/data/3ds`
2nd Back press: `CWD /3ds/data/data`

The third Back press simply uses MiXplorer's cached directory listing (in this case, for `/3ds/data`) and does not actually make any requests.

It's not really a problem when just navigating, I simply need to ignore the dupe directories, but it makes moving or deleting directories impossible, because MiXplorer attempts to interact with the nonexistent child directories and fails in the operation, so I basically can't do directory-level operations any more in ftpd 2.3.

Thanks!

**Comment by deadair3210** [comment]
Not seeing the issue on my 3ds, possibly SD card corruption or ftp client issue

**Comment by mtheall** [comment]
It's possible that your client is using the MLSD/MLST commands which were added in 2.3. Can you provide logs of when the client requests a directory listing?

**Comment by vaguerant** [comment]
Assuming you mean the log from ftpd, here's a quick example:
```
CWD /fbi
200 OK
MLSD
150 Ready
accepted connection from 192.168.1.164:48469
stop listening on 192.168.1.164:48469
closing connection to 192:168.1.164:48469
226 OK
```

**Comment by mtheall** [comment]
Ah yeah I forgot the listing comes over the data channel. I'll have to think of a way to log that unless you can get a client log.

**Comment by vaguerant** [comment]
I actually just found the log on the client-side, but it's not very verbose and I'm not sure if it offers any information that wasn't already visible in ftpd. Still, here it is:

```
I/FTPExplorer>  Answer: 220 Hello!
I/FTPExplorer>  Command: USER <username>
I/FTPExplorer>  Answer: 230 OK
I/FTPExplorer>  Command: FEAT
I/FTPExplorer>  Answer: 211-
I/FTPExplorer>  Answer:  MDTM
I/FTPExplorer>  Answer:  MLST Type*;Size*;Modify*;Perm*;UNIX.mode;
I/FTPExplorer>  Answer:  PASV
I/FTPExplorer>  Answer:  SIZE
I/FTPExplorer>  Answer:  TVFS
I/FTPExplorer>  Answer:  UTF8
I/FTPExplorer>  Answer: 
I/FTPExplorer>  Answer: 211 End
I/FTPExplorer>  Command: OPTS UTF8 ON
I/FTPExplorer>  Answer: 200 OK
I/FTPExplorer>  Command: CWD /
I/FTPExplorer>  Answer: 200 OK
I/FTPExplorer>  Command: PASV
I/FTPExplorer>  Answer: 227 192,168,1,103,19,138
I/FTPExplorer>  Command: MLSD
I/FTPExplorer>  Answer: 150 Ready
I/FTPExplorer>  Answer: 226 OK
D/HUB>  ITEM >> ftp://192.168.1.103:5000/fbi
I/FTPExplorer>  Command: PASV
I/FTPExplorer>  Answer: 227 192,168,1,103,19,139
I/FTPExplorer>  Command: CWD /fbi
I/FTPExplorer>  Answer: 200 OK
I/FTPExplorer>  Command: MLSD
I/FTPExplorer>  Answer: 150 Ready
I/FTPExplorer>  Answer: 226 OK
```

**Comment by mtheall** [comment]
Yeah it's not any new information. We need to see what's going over the data channel. I'll try to add a way to log the information needed.

**Comment by mtheall** [comment]
I think what's happening is that your client is issuing MLSD command and misinterpreting a cdir (current directory) entry type.
