### ISSUE TITLE
Corrupted file after uploading (Switch)

### ISSUE THREAD

**Issue by RicBent** [mtheall/ftpd#89]
When uploading large files they basically always are corrupted.

Example file before and after uploading with ftpd:
![image](https://user-images.githubusercontent.com/12817990/59057751-65c18300-889b-11e9-8504-569b1b647713.png)

I am using Atmosphère 0.8.10 on FW 8.0.1 and am uploading with FileZilla.

**Comment by mtheall** [comment]
Can you find out where the files begin to differ? How "large" is a large file?

**Comment by RicBent** [comment]
The files differ pretty early where a single byte is skipped (at 0x29).

The entire file is ~7.6 MB big.

**Comment by mtheall** [comment]
Looks like 0x0A became 0x0D 0x0A, aka \n becomes \r\n, aka line ending conversion. Check your client's line-ending conversion settings.

**Comment by RicBent** [comment]
Oh, that's it! Had the default file transfer type set to ASCII.

Thanks a lot!
