### ISSUE TITLE
over 700+ items in a folder (small files) don't load

### ISSUE THREAD

**Issue by rygar42** [mtheall/ftpd#92]
i have a directory of small items over 700+ and it won't load even after the custom unix settings in filezilla

**Comment by mtheall** [comment]
As far as I can tell, it works. It just takes a very long time. It gets slower and slower as it goes through the entries. That seems to be a limitation of the system's filesystem service.

**Comment by mtheall** [comment]
I added a configuration option on 3DS to disable gathering mtime in the v3.0.0 branch. This makes large directory listing much faster, but at the cost of everything having an epoch timestamp.
