### ISSUE TITLE
Disconnects after 5 seconds

### ISSUE THREAD

**Issue by 0x6a6576** [mtheall/ftpd#95]
I am having issues with the FTP server keeping the port binded with the interface. Every 5 or so seconds, it just disconnects. Please see the photo below for the error messages:

![ftp_issue](https://user-images.githubusercontent.com/34012310/64481347-96b0ab80-d22e-11e9-8c26-f63cd082d966.jpg)

Do you know what might be causing this issue? This doesn't seem to be a client side issue. I think something is conflicting with the service on the switch itself.

**Comment by aigleron6** [comment]
I have the same issue.
If someone can help us or confirm why that occurs?

**Comment by vert0r** [comment]
Same here

**Comment by mtheall** [comment]
Please reopen if this is still occurring with the v3.0.0 branch.
