### ISSUE TITLE
Wrong time for all files

### ISSUE THREAD

**Issue by Roadhog360** [mtheall/ftpd#97]
Title says it all; All files will be displayed with December 30, 1969 in the FTP Client.

**Comment by mtheall** [comment]
Which client are you using? Can you show which commands it is sending and the responses ftpd is returning?

**Comment by Roadhog360** [comment]
Sure. I'm using WinSCP. I can send a screenshot of the commands the next time I use it. For reference, I reported this to a person who had used this code on the Switch app 'Ultimate Mod Manager' but he said to come here since the code for FTP was basically untouched from the 3DS app.

**Comment by Roadhog360** [comment]
Okay, upon further inspection, it appears to just be folders, not files.

**Comment by Roadhog360** [comment]
It seems these folders print '550 Error getting mtime'.

**Comment by yellows8** [comment]
HOS doesn't support this for directories.
