### ISSUE TITLE
Crash due to logo file

### ISSUE THREAD

**Issue by Jhynjhiruu** [mtheall/ftpd#99]
For some reason, the standard homebrew `logo.bin` file used in this project (and included by default in `makerom`) crashes an iQue 3DS when launched. This can be easily fixed by compiling with [PabloMK7's `homebrewlogo.bin`](https://gbatemp.net/threads/custom-3ds-homebrew-logo-now-without-private-tools.490764/) using makerom's `-logo` parameter.

**Comment by mtheall** [comment]
Can you provide a PR for this?

**Comment by Jhynjhiruu** [comment]
> 
> 
> Can you provide a PR for this?

Done. I _believe_ Pablo is OK with developers using this file without asking, but it might be better to check first.

**Comment by Jhynjhiruu** [comment]
I've talked to Pablo and he reminded me that it's public domain. Of course, it wouldn't hurt to credit him.
